<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }
wp_set_current_user( 1 );
function dc_test_assert($condition,$message){if(!$condition){throw new RuntimeException($message);}}
function dc_fixture_parts($path){$source=file_get_contents($path);preg_match('/<style[^>]*>(.*?)<\/style>/is',$source,$style);preg_match('/<body[^>]*>(.*?)<\/body>/is',$source,$body);return array($body[1]??$source,$style[1]??'');}
$evidence=new Design_Core_Elementor_Runtime_Evidence();
$run_id=wp_generate_uuid4();$created=array();$cleanup=static function()use(&$created,$run_id){foreach(array_unique(array_map('intval',$created)) as $post_id){if($run_id===get_post_meta($post_id,'_design_core_test_artifact',true)){wp_delete_post($post_id,true);}}};register_shutdown_function($cleanup);
try{
$migrator=new Design_Core_Elementor_Registry_Migrator();$migration=$migrator->migrate();dc_test_assert(!is_wp_error($migration),'Registry migration failed.');dc_test_assert($migrator->rollback(),'Registry rollback failed.');$migration=$migrator->migrate();dc_test_assert(!is_wp_error($migration),'Registry re-migration failed.');$evidence->record('registry-migration-rollback','pass',array('component_schema'=>Design_Core_Elementor_Component_Registry::SCHEMA_VERSION),'production-smoke');
$compat=(new Design_Core_Elementor_Compatibility_Validator())->validate();dc_test_assert(!empty($compat['compatible']),'Compatibility validation failed.');
$security=new Design_Core_Elementor_Security_Policy();dc_test_assert(is_wp_error($security->validate_remote_url('http://127.0.0.1/private.png')),'SSRF private IP guard failed.');dc_test_assert(is_wp_error($security->validate_source_size(str_repeat('x',3*1024*1024),'')),'Source-size guard failed.');$evidence->record('security-ssrf-source','pass',array('private_ip'=>'blocked','source_limit'=>'blocked'),'production-smoke');
$breakpoints=(new Design_Core_Elementor_Breakpoint_Registry())->all();dc_test_assert(!empty($breakpoints),'No responsive breakpoints discovered.');
$tokens=new Design_Core_Elementor_Design_Token_Service();$tokens->save(array('colors'=>array('primary'=>'#173f35','accent'=>'#f4a261'),'typography'=>array('heading'=>array('font_family'=>'Inter','font_weight'=>'700')),'spacing'=>array('md'=>24),'radius'=>array('md'=>16)));$global=(new Design_Core_Elementor_Global_Style_Bridge())->sync('v3');dc_test_assert(!is_wp_error($global),'V3 global sync failed.');
$fixtures=array('marketing.html','saas.html','responsive.html');$converter=new Design_Core_Elementor_HTML_Converter();$roundtrip=true;foreach($fixtures as $fixture){list($html,$css)=dc_fixture_parts(DESIGN_CORE_ELEMENTOR_PATH.'tests/fixtures/'.$fixture);$result=$converter->convert_to_elementor($html,$css,'Benchmark '.$fixture);dc_test_assert('success'===($result['status']??''),'Conversion failed for '.$fixture.': '.($result['error']??'unknown'));dc_test_assert(4===(int)($result['design_ir']['schema_version']??0),'Design IR v4 missing for '.$fixture);dc_test_assert(1===(int)($result['build_plan']['build_plan_schema_version']??0),'BuildPlan v1 missing for '.$fixture);dc_test_assert(!empty($result['page_id']),'Page missing for '.$fixture);$page_id=(int)$result['page_id'];$created[]=$page_id;update_post_meta($page_id,'_design_core_test_artifact',$run_id);$stored=json_decode((string)get_post_meta($page_id,'_elementor_data',true),true);$document=\Elementor\Plugin::instance()->documents->get($page_id);$reloaded=$document&&method_exists($document,'get_elements_data')?$document->get_elements_data():$stored;$rendered=\Elementor\Plugin::instance()->frontend->get_builder_content_for_display($page_id,true);if(empty($stored)||empty($reloaded)||''===trim((string)$rendered)){$roundtrip=false;}}
dc_test_assert($roundtrip,'Elementor save/reload/render round trip failed.');$evidence->record('elementor-save-reload-render','pass',array('pages'=>count($created)),'production-smoke');
$page_a='<section><article class="dc-smoke-card"><h4>A</h4><p>One</p></article></section>';$page_b='<section><article class="dc-smoke-card"><h4>B</h4><p>Two</p></article></section>';$a=$converter->convert_to_elementor($page_a,'.dc-smoke-card{padding:24px;border-radius:16px}','Reuse A');$b=$converter->convert_to_elementor($page_b,'.dc-smoke-card{padding:99px;border-radius:2px}','Reuse B');dc_test_assert(!empty($a['page_id'])&&!empty($b['page_id']),'Reuse benchmark pages failed.');foreach(array((int)$a['page_id'],(int)$b['page_id']) as $page_id){$created[]=$page_id;update_post_meta($page_id,'_design_core_test_artifact',$run_id);}dc_test_assert('native-compose'===($a['build_plan']['items'][0]['strategy']??'')&&'reuse-component'===($b['build_plan']['items'][0]['strategy']??''),'Page B did not execute through reuse-component.');$master_ids=array_column(array_merge($a['reuse']??array(),$b['reuse']??array()),'master_id');dc_test_assert(count(array_unique($master_ids))===1,'Page A and Page B did not share one component master.');$master=(new Design_Core_Elementor_Component_Registry())->get($master_ids[0]??'');dc_test_assert(in_array((int)$a['page_id'],$master['usage']['locations']??array(),true)&&in_array((int)$b['page_id'],$master['usage']['locations']??array(),true),'Component usage does not include both pages.');$page_instances=array_filter($master['instances']??array(),static function($instance)use($a,$b){return in_array((int)($instance['location']??0),array((int)$a['page_id'],(int)$b['page_id']),true);});dc_test_assert(2===count($page_instances),'Instance content was not stored independently.');$evidence->record('page-a-page-b-reuse','pass',array('page_a'=>(int)$a['page_id'],'page_b'=>(int)$b['page_id'],'master_id'=>$master_ids[0]??''),'production-smoke');
$widget=(new Design_Core_Elementor_Widget_Generator())->generate('dc-ci-runtime-widget','CI Runtime Widget',array('ci-widget'),array('content_schema'=>array('heading','rich_text','link')));dc_test_assert(!is_wp_error($widget)&&!empty((new Design_Core_Elementor_Widget_Registry())->get('dc-ci-runtime-widget')),'Runtime widget generation failed.');
$readiness=(new Design_Core_Elementor_Production_Readiness())->audit();dc_test_assert('not-ready'!==($readiness['status']??''),'Required production readiness checks failed.');echo wp_json_encode(array('status'=>'pass','pages'=>$created,'breakpoints'=>$breakpoints,'readiness'=>$readiness['status'],'evidence'=>$evidence->all()),JSON_PRETTY_PRINT).PHP_EOL;
}finally{$cleanup();}
