<?php
error_reporting(E_ALL);
define('ABSPATH', __DIR__ . '/');
define('DAY_IN_SECONDS', 86400);
$GLOBALS['posts']=array();$GLOBALS['meta']=array();$GLOBALS['transients']=array();$GLOBALS['next_id']=1;$GLOBALS['assertions']=0;$GLOBALS['failures']=0;
class WP_Error{private $code,$message;public function __construct($c,$m){$this->code=$c;$this->message=$m;}public function get_error_code(){return $this->code;}public function get_error_message(){return $this->message;}}
function is_wp_error($v){return $v instanceof WP_Error;}function add_action(){return true;}function register_post_type(){return true;}function post_type_exists(){return true;}function get_current_user_id(){return 7;}function current_user_can($cap){return $cap==='manage_options'||strpos($cap,'design_core_')===0;}function sanitize_key($v){return strtolower(preg_replace('/[^a-z0-9_\-]/','',(string)$v));}function sanitize_text_field($v){return trim(strip_tags((string)$v));}function wp_json_encode($v,$flags=0){return json_encode($v,$flags);}function wp_generate_uuid4(){return '11111111-2222-4333-8444-555555555555';}
function wp_insert_post($data,$wp_error=false){$id=$GLOBALS['next_id']++;$GLOBALS['posts'][$id]=(object)array('ID'=>$id,'post_title'=>$data['post_title'],'post_author'=>$data['post_author'],'post_type'=>$data['post_type'],'post_status'=>$data['post_status'],'post_date_gmt'=>gmdate('Y-m-d H:i:s'));return $id;}function wp_update_post($data,$wp_error=false){$id=(int)$data['ID'];if(!isset($GLOBALS['posts'][$id]))return new WP_Error('missing','missing');foreach($data as $k=>$v){if($k!=='ID')$GLOBALS['posts'][$id]->$k=$v;}return $id;}
function update_post_meta($id,$key,$value){$GLOBALS['meta'][$id][$key]=array($value);return true;}function add_post_meta($id,$key,$value,$unique=false){$GLOBALS['meta'][$id][$key][]=$value;return true;}function get_post_meta($id,$key='',$single=false){if($key==='')return $GLOBALS['meta'][$id]??array();$vals=$GLOBALS['meta'][$id][$key]??array();return $single?($vals[0]??''):$vals;}
function get_posts($args){$out=array_values($GLOBALS['posts']);if(isset($args['post_type']))$out=array_values(array_filter($out,fn($p)=>$p->post_type===$args['post_type']));if(isset($args['author']))$out=array_values(array_filter($out,fn($p)=>(int)$p->post_author===(int)$args['author']));if(isset($args['meta_key'])){$key=$args['meta_key'];$val=$args['meta_value']??null;$out=array_values(array_filter($out,function($p)use($key,$val){$got=get_post_meta($p->ID,$key,true);return null===$val?(bool)$got:(string)$got===(string)$val;}));}usort($out,fn($a,$b)=>$b->ID<=>$a->ID);$offset=(int)($args['offset']??0);$limit=(int)($args['posts_per_page']??count($out));return array_slice($out,$offset,$limit);}
function set_transient($k,$v,$ttl=0){$GLOBALS['transients'][$k]=$v;return true;}function get_transient($k){return $GLOBALS['transients'][$k]??false;}function delete_transient($k){unset($GLOBALS['transients'][$k]);return true;}
function dc_assert($cond,$msg){$GLOBALS['assertions']++;if(!$cond){$GLOBALS['failures']++;fwrite(STDERR,"FAIL: $msg\n");}}
require dirname(__DIR__,2).'/core/design-run-trace.php';
$hashA=str_repeat('a',64);$hashB=str_repeat('b',64);$source=str_repeat('c',64);
$start=Design_Core_Elementor_Design_Run_Trace::start(array('task'=>'Dimension rebuild','page_id'=>81,'source_hash'=>$source,'client'=>'chatgpt-web'));dc_assert(!is_wp_error($start),'run starts');$run=$start['run']['run_id'];dc_assert($run===Design_Core_Elementor_Design_Run_Trace::active_run_id(),'run becomes active');dc_assert($start['run']['event_count']===1,'start event recorded');
$secret=Design_Core_Elementor_Design_Run_Trace::append_event($run,array('event_type'=>'decision','phase'=>'widget_selection','status'=>'pass','summary'=>'Choose steps','component_id'=>'process-1','decision'=>array('selected_widget'=>'dc-steps','authorization'=>'Bearer secret','nested'=>array('api_key'=>'abc')),'artifact_hash'=>$hashA));dc_assert($secret['event']['decision']['authorization']==='[redacted]','authorization redacted');dc_assert($secret['event']['decision']['nested']['api_key']==='[redacted]','api key redacted');
foreach(array('semantic_qa'=>'semantic_planning','structural_qa'=>'compile','visual_qa'=>'visual_qa','interaction_qa'=>'interaction_qa') as $qa=>$phase){Design_Core_Elementor_Design_Run_Trace::append_event($run,array('event_type'=>'qa','phase'=>$phase,'status'=>'pass','summary'=>$qa.' pass','artifact_hash'=>$hashA,'metadata'=>array($qa=>'pass','schema_validation'=>$qa==='structural_qa'?'pass':'')));}
$get=Design_Core_Elementor_Design_Run_Trace::get($run);dc_assert($get['run']['summary']['promotion_ready']===true,'promotion readiness derives from same artifact evidence');dc_assert($get['run']['summary']['qa']['visual']==='pass','visual pass captured');
Design_Core_Elementor_Design_Run_Trace::append_event($run,array('event_type'=>'correction','phase'=>'correction','status'=>'pass','summary'=>'Changed controls','artifact_hash'=>$hashB));$stale=Design_Core_Elementor_Design_Run_Trace::get($run);dc_assert($stale['run']['summary']['qa']['visual']==='stale','visual QA becomes stale after artifact changes');dc_assert($stale['run']['summary']['promotion_ready']===false,'stale evidence locks promotion readiness');
$result=Design_Core_Elementor_Design_Run_Trace::around('mcp','agent-semantic-component-plan',array('component_type'=>'process-steps','api_key'=>'should-never-store'),function()use($hashB){return array('status'=>'ok','artifact_hash'=>$hashB,'recommendation'=>array('type'=>'direct_widget','widget'=>'dc-steps','score'=>.97,'reason'=>'fit'),'decision_hash'=>str_repeat('d',64));});dc_assert($result['status']==='ok','around preserves result');$events=Design_Core_Elementor_Design_Run_Trace::events($run,array('limit'=>100));$last=end($events['events']);dc_assert($last['operation']==='agent-semantic-component-plan','automatic operation traced');dc_assert(($last['metadata']['selected_widget']??'')==='dc-steps','selected widget summarized');$json=json_encode($events);dc_assert(strpos($json,'should-never-store')===false,'automatic trace never stores input secret');
$components=Design_Core_Elementor_Design_Run_Trace::components($run);dc_assert($components['count']>=1,'component summary produced');$artifacts=Design_Core_Elementor_Design_Run_Trace::artifacts($run);dc_assert(count($artifacts['artifacts'])===2,'artifact history keeps both revisions');
$integrity=Design_Core_Elementor_Design_Run_Trace::get($run);dc_assert($integrity['run']['summary']['integrity']['status']==='pass','event hash chain verifies');
Design_Core_Elementor_Design_Run_Trace::capture_change_ledger_update('design_core_elementor_change_ledger',array(),array(array('id'=>'dc-history-1','action'=>'elementor-save','object_type'=>'post','object_id'=>81,'before_hash'=>str_repeat('1',64),'after_hash'=>str_repeat('2',64),'rollback_of'=>'')));$afterLedger=Design_Core_Elementor_Design_Run_Trace::events($run,array('limit'=>100));$ledgerLast=end($afterLedger['events']);dc_assert(($ledgerLast['metadata']['history_entry_id']??'')==='dc-history-1','Change Ledger mutation links into active run');
$finish=Design_Core_Elementor_Design_Run_Trace::finish($run,array('status'=>'blocked','summary'=>'Waiting for browser QA','artifact_hash'=>$hashB));dc_assert($finish['run']['status']==='blocked','finish status persisted');dc_assert(Design_Core_Elementor_Design_Run_Trace::active_run_id()==='','finished run deactivates');
$list=Design_Core_Elementor_Design_Run_Trace::list_runs(array('limit'=>20));dc_assert($list['count']===1,'run list works');
echo 'design-runs: '.$GLOBALS['assertions'].' assertions, '.$GLOBALS['failures']." failures\n";exit($GLOBALS['failures']?1:0);
