<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }
final class Design_Core_Elementor_Component_Ontology {
 const VERSION=2;
 public static function all(){return array(
 'navigation'=>self::c('Site or section navigation.',array('navigation'),array('responsive'),array(array('menu_items','menu','items')),array('mega-menu','nav-menu','wp-widget-nav_menu'),array('price-list','post-navigation','menu-anchor'),array('commerce','media'),array('container','link-group'),'',array('navigate','menu-toggle')),
 'jump-navigation'=>self::c('In-page navigation with active section tracking.',array('navigation'),array('responsive'),array(array('items','menu_items','links')),array('dc-jump-nav'),array('price-list','post-navigation','menu-anchor'),array('commerce','media'),array(),'dc-jump-nav',array('navigate','same-page-anchor','active-section','keyboard-horizontal-scroll')),
 'hero'=>self::c('Hero/intro section.',array('content','action','media'),array('responsive'),array(),array(),array('price-table','posts'),array('commerce'),array('container','heading','text','media','button'),'',array()),
 'feature-card'=>self::c('Feature or benefit card.',array('content','media'),array('responsive'),array(array('title_text','title','heading'),array('description_text','description','text'),array('selected_icon','image','graphic_element')),array('icon-box','image-box'),array('posts','archive-posts','flip-box'),array('commerce','navigation'),array('container','icon-or-image','heading','text'),'',array()),
 'comparison-table'=>self::c('Comparison matrix.',array('content'),array('responsive','repeater'),array(),array('dc-responsive-table','data-table','table'),array('price-table','price-list'),array('commerce','navigation','media'),array('container-table','row','cell'),'dc-responsive-table',array('compare-data')),
 'data-table'=>self::c('Structured tabular data.',array('content'),array('responsive'),array(),array('dc-responsive-table','data-table','table'),array('price-table','price-list'),array('commerce','navigation','media'),array('container-table','row','cell'),'dc-responsive-table',array('tabular-data')),
 'process-steps'=>self::c('Ordered process/timeline.',array('content'),array('responsive','repeater'),array(array('steps','items','list')),array('dc-steps','timeline','steps'),array('accordion','gallery','dc-global-time-bar','icon-list'),array('commerce','navigation','media','form'),array('container','step-item','heading','text'),'dc-steps',array('ordered-sequence')),
 'faq'=>self::c('Question and answer disclosure group.',array('content'),array('responsive','repeater'),array(array('tabs','items')),array('nested-accordion','accordion','toggle'),array('tabs','price-list'),array('commerce','navigation','media'),array(),'',array('disclosure')),
 'form'=>self::c('Actual data-entry form.',array('form'),array('responsive'),array(array('form_fields','fields')),array('form'),array('search-form','login'),array('navigation','media'),array(),'',array('data-entry','submit')),
 'enquiry-launcher'=>self::c('Launcher that opens a drawer and prefills data.',array('action','form'),array('responsive'),array(array('launcher_placeholder','field_placeholder'),array('drawer_fields','fields')),array('dc-enquiry-drawer'),array('form','search-form'),array('navigation','media'),array(),'dc-enquiry-drawer',array('open-drawer','prefill','focus-trap','escape-close')),
 'cta'=>self::c('Call-to-action block.',array('action','content'),array('responsive'),array(array('button','button_text','text')),array('call-to-action'),array('price-table','form'),array('commerce','navigation'),array('container','heading','text','button'),'',array('activate')),
 'link-group'=>self::c('Editable link group.',array('navigation','content'),array('responsive','repeater'),array(array('icon_list','items','menu_items')),array('icon-list','nav-menu','mega-menu'),array('price-list','post-navigation'),array('commerce','media'),array('container','heading','links'),'',array('navigate')),
 'time-bar'=>self::c('Multi-timezone bar.',array('content'),array('responsive','repeater'),array(array('locations')),array('dc-global-time-bar'),array(),array('commerce','navigation','form'),array(),'dc-global-time-bar',array('live-time')),
 'calculation-panel'=>self::c('Metric/calculation explanation.',array('content'),array('responsive'),array(),array(),array('price-table','price-list'),array('commerce','navigation','form'),array('container','metric-row','heading','text','media'),'',array('explain-calculation')),
 'tabs'=>self::c('Tabbed content.',array('content'),array('responsive'),array(array('tabs','items')),array('nested-tabs','tabs'),array('accordion','price-list'),array('commerce','navigation','media'),array(),'',array('tabbed-content')),
 'image-gallery'=>self::c('Image collection.',array('media'),array('responsive','media'),array(),array('gallery','image-gallery','basic-gallery'),array('posts','products','price-list'),array('commerce','form'),array('container','image'),'',array('media-gallery')),
 'carousel'=>self::c('Carousel/slideshow.',array('media','content'),array('responsive'),array(),array('image-carousel','media-carousel','slides','carousel'),array('posts','price-list'),array('commerce','form'),array(),'',array('carousel-navigation')),
 'testimonial'=>self::c('Customer testimonial.',array('content'),array('responsive'),array(),array('testimonial','testimonial-carousel'),array('reviews','posts'),array('commerce','navigation','form'),array('container','text','heading','media'),'',array()),
 'social-links'=>self::c('Social profile links.',array('social','navigation'),array('responsive'),array(),array('social-icons'),array('share-buttons','price-list'),array('commerce','form'),array('container','links'),'',array('navigate-social')),
 'stats'=>self::c('Numeric metrics.',array('content'),array('responsive'),array(),array('counter'),array('price-table','progress'),array('commerce','navigation'),array('container','heading','text'),'',array('animated-number')),
 'pricing-card'=>self::c('Commercial pricing offer.',array('commerce','action'),array('responsive'),array(),array('price-table'),array('price-list'),array('navigation','media'),array('container','heading','text','button'),'',array('commerce-offer')),
 'posts-list'=>self::c('Dynamic posts/query results.',array('dynamic-content'),array('responsive'),array(),array('loop-grid','posts','archive-posts'),array('price-list','gallery'),array('commerce','form'),array(),'',array('query-content')),
 'search'=>self::c('Site/content search.',array('form','navigation'),array('responsive'),array(),array('search','search-form'),array('form','login'),array('commerce','media'),array(),'',array('search-submit')),
 'contact-info'=>self::c('Structured contact details.',array('content','action'),array('responsive'),array(),array('icon-list'),array('price-list'),array('commerce','media'),array('container','icon-or-image','text'),'',array()),
 'video'=>self::c('Single video player.',array('media'),array('responsive','media'),array(),array('video'),array('media-carousel','gallery'),array('commerce','navigation','form'),array(),'',array('play-media')),
 'media'=>self::c('Single image/media asset.',array('media'),array('responsive','media'),array(array('image','url')),array('image'),array('gallery','carousel'),array('commerce','navigation','form'),array(),'',array())
 );}
 public static function get($type){$all=self::all();return $all[sanitize_key((string)$type)]??null;}public static function types(){return array_keys(self::all());}
 private static function c($description,array $intents,array $caps,array $groups,array $preferred,array $forbidden,array $forbidden_intents,array $composition,$custom,array $behaviors){return array('version'=>self::VERSION,'description'=>$description,'intents'=>$intents,'required_capabilities'=>$caps,'required_control_groups'=>$groups,'preferred_widgets'=>$preferred,'forbidden_widgets'=>$forbidden,'forbidden_intents'=>$forbidden_intents,'native_composition'=>$composition,'custom_widget'=>$custom,'behavior_contract'=>$behaviors);}
}
