<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }

class Design_Core_Elementor_Rest_Controller {
    public function register_routes() {
        $routes = array('/capabilities'=>'get_capabilities','/components'=>'get_components','/sections'=>'get_sections','/widgets'=>'get_widgets','/tokens'=>'get_tokens','/search'=>'search_registry','/diagnostics'=>'get_diagnostics','/readiness'=>'get_readiness','/conversions'=>'get_conversions','/evidence'=>'get_evidence');
        foreach($routes as $route=>$callback){register_rest_route('design-core-elementor/v1',$route,array('methods'=>WP_REST_Server::READABLE,'callback'=>array($this,$callback),'permission_callback'=>array($this,'can_manage'),'args'=>'/search'===$route?array('q'=>array('sanitize_callback'=>'sanitize_text_field')):array()));}
        register_rest_route('design-core-elementor/v1','/elementor-widgets',array('methods'=>WP_REST_Server::READABLE,'callback'=>array($this,'get_elementor_widgets'),'permission_callback'=>array($this,'can_manage'),'args'=>array('source'=>array('sanitize_callback'=>'sanitize_key','default'=>'all'),'q'=>array('sanitize_callback'=>'sanitize_text_field','default'=>''))));
        register_rest_route('design-core-elementor/v1','/elementor-widgets/(?P<widget>[a-zA-Z0-9_-]+)',array('methods'=>WP_REST_Server::READABLE,'callback'=>array($this,'get_elementor_widget'),'permission_callback'=>array($this,'can_manage'),'args'=>array('widget'=>array('sanitize_callback'=>'sanitize_key','required'=>true))));
        register_rest_route('design-core-elementor/v1','/elementor-widget-candidates',array('methods'=>WP_REST_Server::READABLE,'callback'=>array($this,'get_elementor_widget_candidates'),'permission_callback'=>array($this,'can_manage'),'args'=>array('intent'=>array('sanitize_callback'=>'sanitize_key','default'=>''),'controls'=>array('sanitize_callback'=>'sanitize_text_field','default'=>''),'capabilities'=>array('sanitize_callback'=>'sanitize_text_field','default'=>''),'keywords'=>array('sanitize_callback'=>'sanitize_text_field','default'=>''),'limit'=>array('sanitize_callback'=>'absint','default'=>10))));
        register_rest_route('design-core-elementor/v1','/build-preview',array('methods'=>WP_REST_Server::CREATABLE,'callback'=>array($this,'post_build_preview'),'permission_callback'=>array($this,'can_manage')));
        register_rest_route('design-core-elementor/v1','/page-snapshot/(?P<id>\d+)',array('methods'=>WP_REST_Server::READABLE,'callback'=>array($this,'get_page_snapshot'),'permission_callback'=>array($this,'can_manage'),'args'=>array('id'=>array('sanitize_callback'=>'absint','required'=>true))));
        register_rest_route('design-core-elementor/v1','/history',array('methods'=>WP_REST_Server::READABLE,'callback'=>array($this,'get_history'),'permission_callback'=>array($this,'can_manage')));
        register_rest_route('design-core-elementor/v1','/history/(?P<entry>[a-zA-Z0-9_-]+)/rollback',array('methods'=>WP_REST_Server::CREATABLE,'callback'=>array($this,'post_history_rollback'),'permission_callback'=>array($this,'can_manage'),'args'=>array('entry'=>array('sanitize_callback'=>'sanitize_key','required'=>true))));
        register_rest_route('design-core-elementor/v1','/figma/design-ir',array('methods'=>WP_REST_Server::CREATABLE,'callback'=>array($this,'post_figma_design_ir'),'permission_callback'=>array($this,'can_manage')));
        register_rest_route('design-core-elementor/v1','/visual-feedback',array('methods'=>WP_REST_Server::CREATABLE,'callback'=>array($this,'post_visual_feedback'),'permission_callback'=>array($this,'can_manage')));
        register_rest_route('design-core-elementor/v1','/visual-correction',array('methods'=>WP_REST_Server::CREATABLE,'callback'=>array($this,'post_visual_correction'),'permission_callback'=>array($this,'can_manage')));
        register_rest_route('design-core-elementor/v1','/benchmarks',array('methods'=>WP_REST_Server::READABLE,'callback'=>array($this,'get_benchmarks'),'permission_callback'=>array($this,'can_manage')));
        register_rest_route('design-core-elementor/v1','/benchmarks/(?P<id>[a-zA-Z0-9_-]+)/planning',array('methods'=>WP_REST_Server::READABLE,'callback'=>array($this,'get_benchmark_planning'),'permission_callback'=>array($this,'can_manage'),'args'=>array('id'=>array('sanitize_callback'=>'sanitize_key','required'=>true))));
        register_rest_route('design-core-elementor/v1','/page-shell/compile',array('methods'=>WP_REST_Server::CREATABLE,'callback'=>array($this,'post_page_shell_compile'),'permission_callback'=>array($this,'can_manage')));
        register_rest_route('design-core-elementor/v1','/section-explain/(?P<master>[a-zA-Z0-9_-]+)',array('methods'=>WP_REST_Server::READABLE,'callback'=>array($this,'get_section_explain'),'permission_callback'=>array($this,'can_manage'),'args'=>array('master'=>array('sanitize_callback'=>'sanitize_text_field','required'=>true))));
        register_rest_route('design-core-elementor/v1','/section-explain',array('methods'=>WP_REST_Server::CREATABLE,'callback'=>array($this,'post_section_explain'),'permission_callback'=>array($this,'can_manage')));
        register_rest_route('design-core-elementor/v1','/agent/tools',array('methods'=>WP_REST_Server::READABLE,'callback'=>array($this,'get_agent_tools'),'permission_callback'=>array($this,'can_manage'),'args'=>array('q'=>array('sanitize_callback'=>'sanitize_text_field','default'=>''))));
        register_rest_route('design-core-elementor/v1','/agent/tools/(?P<tool>[a-zA-Z0-9_-]+)/schema',array('methods'=>WP_REST_Server::READABLE,'callback'=>array($this,'get_agent_tool_schema'),'permission_callback'=>array($this,'can_manage'),'args'=>array('tool'=>array('sanitize_callback'=>'sanitize_key','required'=>true))));
        register_rest_route('design-core-elementor/v1','/agent/execute',array('methods'=>WP_REST_Server::CREATABLE,'callback'=>array($this,'post_agent_execute'),'permission_callback'=>array($this,'can_manage')));
    }
    public function can_manage(){return current_user_can('manage_options');}
    public function get_capabilities(){return rest_ensure_response((new Design_Core_Elementor_Capability_Scanner())->scan());}
    public function get_components(){return rest_ensure_response((new Design_Core_Elementor_Component_Registry())->all());}
    public function get_sections(){return rest_ensure_response((new Design_Core_Elementor_Section_Registry())->all());}
    public function get_widgets(){return rest_ensure_response((new Design_Core_Elementor_Widget_Registry())->all());}
    public function get_tokens(){return rest_ensure_response((new Design_Core_Elementor_Design_Token_Service())->all());}
    public function get_readiness(){return rest_ensure_response((new Design_Core_Elementor_Production_Readiness())->audit());}
    public function get_conversions(){return rest_ensure_response(Design_Core_Elementor_Observability::recent());}
    public function get_evidence(){return rest_ensure_response((new Design_Core_Elementor_Runtime_Evidence())->all());}
    public function get_elementor_widgets(WP_REST_Request $r){$c=(new Design_Core_Elementor_Widget_Intelligence())->catalog((string)$r->get_param('source'),(string)$r->get_param('q'));if(!empty($c['error']))return new WP_Error('design_core_elementor_widgets_unavailable',$c['error'],array('status'=>503));$c['widgets']=array_values((array)($c['widgets']??array()));return rest_ensure_response(Design_Core_Elementor_Widget_Intelligence::transport_safe($c));}
    public function get_elementor_widget(WP_REST_Request $r){$d=(new Design_Core_Elementor_Widget_Intelligence())->inspect((string)$r->get_param('widget'));return is_wp_error($d)?$d:rest_ensure_response(Design_Core_Elementor_Widget_Intelligence::transport_safe($d));}
    public function get_elementor_widget_candidates(WP_REST_Request $r){$q=array('intent'=>(string)$r->get_param('intent'),'controls'=>$this->csv($r->get_param('controls')),'capabilities'=>$this->csv($r->get_param('capabilities')),'keywords'=>$this->csv($r->get_param('keywords')));return rest_ensure_response(array('requirements'=>$q,'candidates'=>(new Design_Core_Elementor_Widget_Intelligence())->find_candidates($q,(int)$r->get_param('limit'))));}
    public function post_build_preview(WP_REST_Request $r){$b=$this->json_body($r);if(is_wp_error($b))return $b;$s=new Design_Core_Elementor_Build_Plan_Preview();$x=!empty($b['design_ir'])&&is_array($b['design_ir'])?$s->preview_ir($b['design_ir'],$b['adapter_target']??'auto'):$s->preview_source((string)($b['html']??''),(string)($b['css']??''),'rest-preview',$b['adapter_target']??'auto');return is_wp_error($x)?$x:rest_ensure_response(Design_Core_Elementor_Change_Ledger::transport_safe($x));}
    public function get_page_snapshot(WP_REST_Request $r){$x=(new Design_Core_Elementor_Page_Snapshot())->snapshot((int)$r->get_param('id'));return is_wp_error($x)?$x:rest_ensure_response(Design_Core_Elementor_Change_Ledger::transport_safe($x));}
    public function get_history(){return rest_ensure_response((new Design_Core_Elementor_Change_Ledger())->summaries());}
    public function post_history_rollback(WP_REST_Request $r){$x=(new Design_Core_Elementor_Change_Ledger())->rollback((string)$r->get_param('entry'));return is_wp_error($x)?$x:rest_ensure_response($x);}
    public function post_figma_design_ir(WP_REST_Request $r){$b=$this->json_body($r);if(is_wp_error($b))return $b;if(!empty($b['figma_url'])){$payload=(new Design_Core_Elementor_Figma_Transport())->read_url((string)$b['figma_url'],array('resolve_image_fills'=>true));if(is_wp_error($payload))return $payload;$x=(new Design_Core_Elementor_Figma_Design_IR_Adapter())->convert($payload,(string)($b['node_id']??''));}else{$f=is_array($b['figma']??null)?$b['figma']:$b;$x=(new Design_Core_Elementor_Figma_Design_IR_Adapter())->convert($f,(string)($b['node_id']??''));}return is_wp_error($x)?$x:rest_ensure_response($x);}
    public function post_visual_feedback(WP_REST_Request $r){$b=$this->json_body($r);if(is_wp_error($b))return $b;$x=(new Design_Core_Elementor_Visual_Feedback_Engine())->evaluate_targets((string)($b['reference_target']??''),(string)($b['candidate_target']??''),array('page_id'=>(int)($b['page_id']??0),'target_similarity'=>(float)($b['target_similarity']??0.95)));return is_wp_error($x)?$x:rest_ensure_response(Design_Core_Elementor_Change_Ledger::transport_safe($x));}
    public function post_visual_correction(WP_REST_Request $r){$b=$this->json_body($r);if(is_wp_error($b))return $b;if(empty($b['confirm']))return new WP_Error('design_core_confirmation_required','Visual correction mutates Elementor and requires confirm=true.',array('status'=>400));$x=(new Design_Core_Elementor_Visual_Correction_Service())->run((string)($b['reference_target']??''),(string)($b['candidate_target']??''),(int)($b['max_iterations']??3),(float)($b['target_similarity']??0.95),array('page_id'=>(int)($b['page_id']??0)));return is_wp_error($x)?$x:rest_ensure_response(Design_Core_Elementor_Change_Ledger::transport_safe($x));}
    public function get_benchmarks(){return rest_ensure_response((new Design_Core_Elementor_Design_Benchmark_Corpus())->catalog());}
    public function get_benchmark_planning(WP_REST_Request $r){$x=(new Design_Core_Elementor_Design_Benchmark_Corpus())->planning((string)$r->get_param('id'));return is_wp_error($x)?$x:rest_ensure_response(Design_Core_Elementor_Change_Ledger::transport_safe($x));}
    public function post_page_shell_compile(WP_REST_Request $r){$b=$this->json_body($r);if(is_wp_error($b))return $b;$x=(new Design_Core_Elementor_Page_Shell())->compile((string)($b['shell']??''),(array)($b['bindings']??array()));return is_wp_error($x)?$x:rest_ensure_response($x);}
    public function get_section_explain(WP_REST_Request $r){$x=(new Design_Core_Elementor_Section_Explainability())->explain_master((string)$r->get_param('master'));return is_wp_error($x)?$x:rest_ensure_response(Design_Core_Elementor_Change_Ledger::transport_safe($x));}
    public function post_section_explain(WP_REST_Request $r){$b=$this->json_body($r);if(is_wp_error($b))return $b;return rest_ensure_response((new Design_Core_Elementor_Section_Explainability())->explain_candidate((array)($b['fingerprint']??$b)));}
    public function get_agent_tools(WP_REST_Request $r){return rest_ensure_response((new Design_Core_Elementor_Agent_Gateway())->catalog((string)$r->get_param('q')));}
    public function get_agent_tool_schema(WP_REST_Request $r){$x=(new Design_Core_Elementor_Agent_Gateway())->schema((string)$r->get_param('tool'));return is_wp_error($x)?$x:rest_ensure_response($x);}
    public function post_agent_execute(WP_REST_Request $r){$b=$this->json_body($r);if(is_wp_error($b))return $b;$x=(new Design_Core_Elementor_Agent_Gateway())->execute((string)($b['name']??''),(array)($b['arguments']??array()));return is_wp_error($x)?$x:rest_ensure_response(Design_Core_Elementor_Change_Ledger::transport_safe($x));}
    public function search_registry(WP_REST_Request $r){$q=(string)$r->get_param('q');return rest_ensure_response(array('components'=>(new Design_Core_Elementor_Component_Registry())->search($q),'sections'=>(new Design_Core_Elementor_Section_Registry())->search($q),'widgets'=>(new Design_Core_Elementor_Widget_Registry())->search($q)));}
    public function get_diagnostics(){return rest_ensure_response(array('version'=>DESIGN_CORE_ELEMENTOR_VERSION,'component_schema_version'=>Design_Core_Elementor_Component_Registry::SCHEMA_VERSION,'section_schema_version'=>Design_Core_Elementor_Section_Registry::SCHEMA_VERSION,'section_fingerprint_version'=>Design_Core_Elementor_Section_Fingerprint_Service::VERSION,'widget_schema_version'=>Design_Core_Elementor_Widget_Registry::SCHEMA_VERSION,'elementor_control_schema_version'=>Design_Core_Elementor_Control_Schema_Registry::SCHEMA_VERSION,'widget_intelligence_profile_version'=>Design_Core_Elementor_Widget_Intelligence::PROFILE_VERSION,'layout_intelligence_version'=>Design_Core_Elementor_Layout_Intelligence::VERSION,'build_preview_schema_version'=>Design_Core_Elementor_Build_Plan_Preview::SCHEMA_VERSION,'build_simulator_version'=>Design_Core_Elementor_Build_Plan_Simulator::VERSION,'page_shell_schema_version'=>Design_Core_Elementor_Page_Shell::SCHEMA_VERSION,'page_snapshot_schema_version'=>Design_Core_Elementor_Page_Snapshot::SCHEMA_VERSION,'history_schema_version'=>Design_Core_Elementor_Change_Ledger::SCHEMA_VERSION,'figma_transport_version'=>Design_Core_Elementor_Figma_Transport::VERSION,'figma_adapter_version'=>Design_Core_Elementor_Figma_Design_IR_Adapter::VERSION,'visual_feedback_version'=>Design_Core_Elementor_Visual_Feedback_Engine::VERSION,'visual_correction_version'=>Design_Core_Elementor_Visual_Correction_Service::VERSION,'benchmark_corpus_version'=>Design_Core_Elementor_Design_Benchmark_Corpus::VERSION,'agent_gateway_version'=>Design_Core_Elementor_Agent_Gateway::VERSION,'token_schema_version'=>Design_Core_Elementor_Design_Token_Service::SCHEMA_VERSION,'design_ir_schema_version'=>Design_Core_Elementor_Design_IR::SCHEMA_VERSION,'readiness'=>(new Design_Core_Elementor_Production_Readiness())->audit(),'evidence'=>(new Design_Core_Elementor_Runtime_Evidence())->all()));}
    private function csv($v){$i=is_array($v)?$v:explode(',',(string)$v);$i=array_map(static function($x){return sanitize_key(trim((string)$x));},$i);return array_values(array_unique(array_filter($i)));}
    private function json_body(WP_REST_Request $r){$b=$r->get_json_params();if(!is_array($b))$b=array();$e=wp_json_encode($b);if(is_string($e)&&strlen($e)>2097152)return new WP_Error('design_core_rest_payload_too_large','Request payload exceeds the 2 MB Design Core limit.',array('status'=>413));return $b;}
}
