<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }
/** Identity-first catalog used by Semantic Planning V2. */
final class Design_Core_Elementor_Semantic_Widget_Intelligence_V2 extends Design_Core_Elementor_Widget_Intelligence {
 const VERSION=2; private $registry_v2; private $provider_v2; private $cache_v2=null;
 public function __construct(?Design_Core_Elementor_Control_Schema_Registry $registry=null,$provider=null){$this->registry_v2=$registry?:new Design_Core_Elementor_Control_Schema_Registry();$this->provider_v2=is_callable($provider)?$provider:array($this,'runtime_widgets_v2');parent::__construct($this->registry_v2,$this->provider_v2);}
 public function catalog($source='all',$query=''){if(null===$this->cache_v2)$this->cache_v2=$this->build();$source=sanitize_key((string)$source);$wanted=Design_Core_Elementor_Semantic_Tokenizer::tokens((string)$query,true);if('all'===$source&&!$wanted)return $this->cache_v2;$widgets=array_filter($this->cache_v2['widgets'],static function($w)use($source,$wanted){if('all'!==$source&&($w['source']??'')!==$source)return false;$tokens=(array)($w['semantic']['tokens']??array());foreach($wanted as $t){if(!in_array($t,$tokens,true))return false;}return true;});$out=$this->cache_v2;$out['widgets']=$widgets;$out['filtered_count']=count($widgets);return $out;}
 public function inspect($widget_type){$widget_type=sanitize_key((string)$widget_type);$c=$this->catalog();return isset($c['widgets'][$widget_type])?$c['widgets'][$widget_type]:new WP_Error('design_core_widget_not_found','The requested Elementor widget is not registered.');}
 public function runtime_widgets_v2(){if(!class_exists('\\Elementor\\Plugin'))return new WP_Error('design_core_elementor_runtime_missing','Elementor runtime is not available.');try{$widgets=\Elementor\Plugin::instance()->widgets_manager->get_widget_types();return is_array($widgets)?$widgets:new WP_Error('design_core_widgets_invalid','Elementor returned an invalid widget registry.');}catch(Throwable $e){return new WP_Error('design_core_widgets_runtime_error',$e->getMessage());}}
 private function build(){$out=array('profile_version'=>self::VERSION,'schema_version'=>Design_Core_Elementor_Control_Schema_Registry::SCHEMA_VERSION,'counts'=>array('all'=>0,'core'=>0,'pro'=>0,'design_core'=>0,'third_party'=>0),'widgets'=>array(),'error'=>'');$widgets=call_user_func($this->provider_v2);if(is_wp_error($widgets)){$out['error']=$widgets->get_error_message();return $out;}foreach((array)$widgets as $registered=>$widget){if(!is_object($widget))continue;$row=$this->summarize((string)$registered,$widget);$out['widgets'][$row['name']]=$row;$out['counts']['all']++;if(isset($out['counts'][$row['source']]))$out['counts'][$row['source']]++;}uasort($out['widgets'],static fn($a,$b)=>strcasecmp((string)$a['title'],(string)$b['title']));return $out;}
 private function summarize($registered,$widget){$name=sanitize_key((string)$this->safe_call($widget,'get_name',$registered));if(!$name)$name=sanitize_key($registered);$class=get_class($widget);$source=Design_Core_Elementor_Widget_Intelligence::classify_widget_class($class);$title=(string)$this->safe_call($widget,'get_title',$name);$categories=$this->strings($this->safe_call($widget,'get_categories',array()));$keywords=$this->strings($this->safe_call($widget,'get_keywords',array()));$schema=$this->registry_v2->schema('widget',$name);$tokens=Design_Core_Elementor_Semantic_Tokenizer::tokens(array_merge(array($name,$title,$class),$categories,$keywords),true);return array('name'=>$name,'title'=>$title,'class'=>$class,'source'=>$source,'categories'=>$categories,'keywords'=>$keywords,'control_count'=>(int)($schema['statistics']['flattened']??0),'responsive_control_count'=>(int)($schema['statistics']['responsive']??0),'schema_version'=>(int)($schema['schema_version']??0),'schema_fingerprint'=>(string)($schema['fingerprint']??''),'schema_statistics'=>(array)($schema['statistics']??array()),'capabilities'=>(array)($schema['capabilities']??array()),'semantic'=>$this->semantic($tokens,array_keys((array)($schema['controls']??array()))));}
 private function semantic(array $tokens,array $control_names){$rules=array('commerce'=>array('woocommerce'=>1,'product'=>.95,'cart'=>1,'checkout'=>1,'price'=>.75),'form'=>array('form'=>1,'field'=>.75,'input'=>.75,'login'=>.9,'search'=>.55),'navigation'=>array('navigation'=>1,'menu'=>.95,'breadcrumb'=>.95,'nav'=>.8),'dynamic-content'=>array('loop'=>1,'posts'=>.9,'archive'=>.9,'query'=>.85),'media'=>array('image'=>.9,'gallery'=>1,'video'=>1,'media'=>.85,'carousel'=>.95),'action'=>array('button'=>1,'cta'=>1,'link'=>.65),'social'=>array('social'=>1,'share'=>.9),'content'=>array('heading'=>1,'title'=>.8,'text'=>.85,'editor'=>.9,'testimonial'=>.9),'layout'=>array('container'=>1,'section'=>.9,'spacer'=>.9,'divider'=>.9,'column'=>.9));$scores=array_fill_keys(array_keys($rules),0.0);foreach($rules as $intent=>$signals){foreach($signals as $term=>$weight){if(Design_Core_Elementor_Semantic_Tokenizer::has_all($tokens,$term))$scores[$intent]=max($scores[$intent],(float)$weight);}}foreach($control_names as $control){$c=sanitize_key((string)$control);if(in_array($c,array('form_fields','fields','submit_actions'),true))$scores['form']+=.25;if(in_array($c,array('menu_items','menu'),true))$scores['navigation']+=.3;if(in_array($c,array('price','sale_price','currency_symbol'),true))$scores['commerce']+=.3;}arsort($scores,SORT_NUMERIC);$primary='general';$max=0;$intents=array();foreach($scores as $intent=>$score){$score=min(1,(float)$score);if($score>$max){$primary=$intent;$max=$score;}if($score>=.5)$intents[]=$intent;}if(!$intents){$intents=array('general');$primary='general';}return array('version'=>self::VERSION,'primary_intent'=>$primary,'intents'=>$intents,'confidence'=>round(min(1,$max),4),'intent_scores'=>$scores,'tokens'=>$tokens,'evidence_policy'=>'identity-first-exact-token-controls-secondary');}
 private function safe_call($widget,$method,$default){try{if(!method_exists($widget,$method))return $default;$r=new ReflectionMethod($widget,$method);if(!$r->isPublic()||$r->getNumberOfRequiredParameters()>0)return $default;$v=$widget->{$method}();return null===$v?$default:$v;}catch(Throwable $e){return $default;}}
 private function strings($v){$out=array();foreach((array)$v as $x){if(is_scalar($x)&&''!==(string)$x)$out[]=(string)$x;}return array_values(array_unique($out));}
}
