<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }
/** Runtime-schema-backed suitability scorer with hard rejection reasons. */
final class Design_Core_Elementor_Widget_Fit_Engine {
 const VERSION=2; private $registry; public function __construct(?Design_Core_Elementor_Control_Schema_Registry $registry=null){$this->registry=$registry?:new Design_Core_Elementor_Control_Schema_Registry();}
 public function evaluate(array $widget,array $contract,array $requirements=array()){
  $name=sanitize_key((string)($widget['name']??''));$semantic=(array)($widget['semantic']??array());$primary=sanitize_key((string)($semantic['primary_intent']??''));$intents=array_values(array_unique(array_map('sanitize_key',(array)($semantic['intents']??array()))));$supports=array_values(array_unique(array_map('sanitize_key',(array)($widget['capabilities']['supports']??array()))));$schema=$this->registry->schema('widget',$name);$controls=self::paths((array)($schema['controls']??array()));$reject=array();$evidence=array();
  $required_caps=array_values(array_unique(array_merge((array)($contract['required_capabilities']??array()),(array)($requirements['required_capabilities']??array()))));foreach($required_caps as $cap){$cap=sanitize_key((string)$cap);if(!$cap)continue;if(!in_array($cap,$supports,true))$reject[]='missing_capability:'.$cap;else $evidence[]='capability:'.$cap;}
  $forbidden=array_map('sanitize_key',array_merge((array)($contract['forbidden_widgets']??array()),(array)($requirements['forbidden_widgets']??array())));if(in_array($name,$forbidden,true))$reject[]='forbidden_widget:'.$name;$forbidden_intents=array_map('sanitize_key',array_merge((array)($contract['forbidden_intents']??array()),(array)($requirements['forbidden_intents']??array())));if($primary&&in_array($primary,$forbidden_intents,true))$reject[]='primary_intent_conflict:'.$primary;
  $groups=(array)($contract['required_control_groups']??array());foreach((array)($requirements['required_control_groups']??array()) as $g)$groups[]=(array)$g;foreach($groups as $group){$group=array_values(array_filter(array_map('sanitize_key',(array)$group)));if(!$group)continue;$m=self::match($controls,$group);if(!$m)$reject[]='missing_control_group:'.implode('|',$group);else $evidence[]='control:'.$m;}foreach((array)($requirements['required_controls']??array()) as $required){$required=sanitize_key((string)$required);if(!$required)continue;$m=self::match($controls,array($required));if(!$m)$reject[]='missing_control:'.$required;else $evidence[]='control:'.$m;}
  $behavior=array_values(array_unique(array_map('sanitize_key',array_merge((array)($contract['behavior_contract']??array()),(array)($requirements['behaviors']??array())))));$known=self::behaviors($name);$unverified=array_values(array_diff($behavior,$known));foreach(array_intersect($behavior,$known) as $b)$evidence[]='behavior:'.$b;
  if($reject)return array('status'=>'rejected','score'=>0.0,'name'=>$name,'rejections'=>array_values(array_unique($reject)),'evidence'=>array_values(array_unique($evidence)),'schema_fingerprint'=>(string)($widget['schema_fingerprint']??$schema['fingerprint']??''),'unverified_behaviors'=>$unverified);
  $score=0;$breakdown=array();$preferred=array_map('sanitize_key',array_merge((array)($contract['preferred_widgets']??array()),(array)($requirements['preferred_widgets']??array())));if(in_array($name,$preferred,true)){$score+=.30;$breakdown['preferred_widget']=.30;}$wanted=array_map('sanitize_key',(array)($contract['intents']??array()));if($primary&&in_array($primary,$wanted,true)){$score+=.20;$breakdown['primary_intent']=.20;}elseif(array_intersect($intents,$wanted)){$score+=.12;$breakdown['secondary_intent']=.12;}$tokens=(array)($semantic['tokens']??array());$overlap=Design_Core_Elementor_Semantic_Tokenizer::overlap($tokens,array_merge((array)($requirements['keywords']??array()),$wanted));$identity=min(.20,.20*$overlap);$score+=$identity;if($identity)$breakdown['identity']=round($identity,4);$need=max(1,count($required_caps)+count($groups)+count((array)($requirements['required_controls']??array())));$runtime=min(.20,.20*count(array_unique($evidence))/$need);$score+=$runtime;if($runtime)$breakdown['runtime_contract']=round($runtime,4);if((!empty($requirements['repeated'])||in_array('repeater',$required_caps,true))&&in_array('repeater',$supports,true)){$score+=.08;$breakdown['repeater_editability']=.08;}if(in_array('responsive',$supports,true)){$score+=.04;$breakdown['responsive_editability']=.04;}if(in_array($name,array('text-editor','button','heading','html'),true)&&!empty($requirements['composite_component'])){$score-=.25;$breakdown['generic_widget_penalty']=-.25;}if($unverified){$pen=min(.18,.06*count($unverified));$score-=$pen;$breakdown['behavior_gap_penalty']=-$pen;}$score=max(0,min(1,round($score,4)));return array('status'=>'compatible','score'=>$score,'name'=>$name,'rejections'=>array(),'evidence'=>array_values(array_unique($evidence)),'breakdown'=>$breakdown,'unverified_behaviors'=>$unverified,'schema_fingerprint'=>(string)($widget['schema_fingerprint']??$schema['fingerprint']??''),'control_count'=>count($controls));
 }
 private static function behaviors($name){$map=array('mega-menu'=>array('navigate','menu-toggle'),'nav-menu'=>array('navigate','menu-toggle'),'accordion'=>array('disclosure'),'nested-accordion'=>array('disclosure'),'toggle'=>array('disclosure'),'form'=>array('data-entry','submit'),'button'=>array('activate','navigate'),'icon-list'=>array('navigate'),'dc-global-time-bar'=>array('live-time'),'dc-steps'=>array('ordered-sequence'),'dc-responsive-table'=>array('compare-data','tabular-data'),'dc-jump-nav'=>array('navigate','same-page-anchor','active-section','keyboard-horizontal-scroll'),'dc-enquiry-drawer'=>array('data-entry','open-drawer','prefill','focus-trap','escape-close'),'tabs'=>array('tabbed-content'),'nested-tabs'=>array('tabbed-content'),'image-carousel'=>array('carousel-navigation'),'media-carousel'=>array('carousel-navigation'),'social-icons'=>array('navigate-social'),'counter'=>array('animated-number'),'price-table'=>array('commerce-offer'),'loop-grid'=>array('query-content'),'posts'=>array('query-content'),'search'=>array('search-submit'),'video'=>array('play-media'));return $map[$name]??array();}
 private static function paths(array $controls,$parent=''){$out=array();foreach($controls as $key=>$def){if(!is_array($def))continue;$name=sanitize_key((string)($def['name']??$key));if(!$name)continue;$path=$parent?$parent.'.'.$name:$name;$out[]=$path;if(!empty($def['fields'])&&is_array($def['fields']))$out=array_merge($out,self::paths($def['fields'],$path));}return array_values(array_unique($out));}
 private static function match(array $paths,array $needles){foreach($needles as $needle){foreach($paths as $path){$leaf=false!==strrpos($path,'.')?substr($path,strrpos($path,'.')+1):$path;if($path===$needle||$leaf===$needle||str_starts_with($leaf,$needle.'_'))return $path;}}return '';}
}
