<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }

/** Build the six main-content roots that follow the current staged sections. */
function design_core_air_page_completion_elements( array $assets ) {
    $id = static function ( $name ) { return substr( md5( 'dc-air-page-completion|' . $name ), 0, 8 ); };
    $size = static function ( $value, $unit = 'px' ) { return array( 'size' => $value, 'unit' => $unit, 'sizes' => array() ); };
    $dims = static function ( $top, $right, $bottom, $left, $unit = 'px' ) { return array( 'top' => $top, 'right' => $right, 'bottom' => $bottom, 'left' => $left, 'unit' => $unit, 'isLinked' => false ); };
    $gap = static function ( $value ) { return array( 'column' => (string) $value, 'row' => (string) $value, 'isLinked' => true, 'unit' => 'px', 'size' => $value ); };
    $container = static function ( $name, array $settings, array $children = array() ) use ( $id ) { return array( 'id' => $id( $name ), 'elType' => 'container', 'isInner' => false, 'settings' => $settings, 'elements' => $children ); };
    $widget = static function ( $name, $type, array $settings ) use ( $id ) { return array( 'id' => $id( $name ), 'elType' => 'widget', 'widgetType' => $type, 'isInner' => false, 'settings' => $settings, 'elements' => array() ); };
    $heading = static function ( $name, $text, $level = 'h2', $class = '' ) use ( $widget, $size ) { return $widget( $name, 'heading', array( 'title' => $text, 'header_size' => $level, 'title_color' => '#131417', 'typography_typography' => 'custom', 'typography_font_family' => 'Geist', 'typography_font_size' => $size( 'h2' === $level ? 34 : 18 ), 'typography_font_weight' => '600', 'typography_line_height' => $size( 1.1, 'em' ), 'typography_letter_spacing' => $size( 'h2' === $level ? -2.2 : -.6 ), 'typography_font_size_mobile' => $size( 'h2' === $level ? 26 : 17 ), '_css_classes' => $class ) ); };
    $text = static function ( $name, $content, $class = '', $font_size = 14, $color = '#5a5d63' ) use ( $widget, $size ) { return $widget( $name, 'text-editor', array( 'editor' => $content, 'text_color' => $color, 'typography_typography' => 'custom', 'typography_font_family' => 'Poppins', 'typography_font_size' => $size( $font_size ), 'typography_font_weight' => '400', 'typography_line_height' => $size( 1.68, 'em' ), 'typography_font_size_mobile' => $size( max( 13, $font_size - 1 ) ), '_css_classes' => $class ) ); };
    $root = static function ( $name, $anchor, $class, $background, array $children, $custom_css = '' ) use ( $container, $dims, $gap ) { return $container( $name, array( 'content_width' => 'full', 'flex_direction' => 'column', 'flex_gap' => $gap( 0 ), 'padding' => $dims( 110, 0, 110, 0 ), 'padding_tablet' => $dims( 76, 0, 76, 0 ), 'padding_mobile' => $dims( 64, 0, 64, 0 ), 'background_background' => 'classic', 'background_color' => $background, 'html_tag' => 'section', '_element_id' => $anchor, 'css_classes' => $class, 'custom_css' => $custom_css ), $children ); };
    $inner = static function ( $name, array $children, $class = '', $section_gap = 44 ) use ( $container, $dims, $gap ) { return $container( $name, array( 'content_width' => 'boxed', 'flex_direction' => 'column', 'flex_gap' => $gap( $section_gap ), 'padding' => $dims( 0, 0, 0, 0 ), 'css_classes' => trim( $class . ' dc-global-container' ) ), $children ); };
    $intro = static function ( $name, $title, $lead ) use ( $container, $heading, $text, $gap, $dims ) { return $container( $name . '-intro', array( 'content_width' => 'full', 'flex_direction' => 'column', 'flex_gap' => $gap( 16 ), 'flex_gap_mobile' => $gap( 14 ), 'padding' => $dims( 0, 0, 0, 0 ), 'css_classes' => 'dc-section-intro' ), array( $heading( $name . '-title', $title, 'h2', 'dc-section-title' ), $text( $name . '-lead', $lead, 'dc-section-lead', 16 ) ) ); };

    /* Sticky page navigation. */
    $jump_menu = $widget( 'jumpbar-menu', 'nav-menu', array(
        'menu_name' => 'On this page', 'menu' => 'design-core-air-section-navigation', 'layout' => 'horizontal', 'align_items' => 'start', 'pointer' => 'underline', 'animation_line' => 'slide', 'dropdown' => 'none', 'toggle' => 'none',
        'menu_typography_typography' => 'custom', 'menu_typography_font_family' => 'Poppins', 'menu_typography_font_size' => $size( 14 ), 'menu_typography_font_weight' => '600',
        'color_menu_item' => '#5a5d63', 'color_menu_item_hover' => '#131417', 'pointer_color_menu_item_hover' => '#d6d3cd', 'color_menu_item_active' => '#131417', 'pointer_color_menu_item_active' => '#fbc925',
        'padding_horizontal_menu_item' => $size( 0 ), 'padding_vertical_menu_item' => $size( 22 ), 'menu_space_between' => $size( 34 ), '_css_classes' => 'dc-jumpbar-menu',
    ) );
    $jump_cta = $widget( 'jumpbar-cta', 'button', array( 'text' => 'Talk to our team', 'link' => array( 'url' => '#enquiry' ), 'align' => 'right', 'typography_typography' => 'custom', 'typography_font_family' => 'Poppins', 'typography_font_size' => $size( 13.5 ), 'typography_font_weight' => '600', 'button_text_color' => '#131417', 'background_background' => 'classic', 'background_color' => '#fbc925', 'button_background_hover_color' => '#f7d85f', 'hover_color' => '#131417', 'button_hover_animation' => 'float', 'border_radius' => $dims( 6, 6, 6, 6 ), 'text_padding' => $dims( 12, 22, 12, 22 ), 'hide_tablet' => 'hidden-tablet', 'hide_mobile' => 'hidden-mobile', '_css_classes' => 'dc-jumpbar-cta' ) );
    $jump_inner = $container( 'jumpbar-inner', array( 'content_width' => 'boxed', 'flex_direction' => 'row', 'flex_justify_content' => 'space-between', 'flex_align_items' => 'center', 'flex_gap' => $gap( 24 ), 'padding' => $dims( 0, 0, 0, 0 ), 'css_classes' => 'dc-jumpbar-inner dc-global-container' ), array( $jump_menu, $jump_cta ) );
    $jumpbar = $container( 'jumpbar-root', array( 'content_width' => 'full', 'flex_direction' => 'column', 'flex_gap' => $gap( 0 ), 'padding' => $dims( 0, 0, 0, 0 ), 'background_background' => 'classic', 'background_color' => '#ffffff', 'border_border' => 'solid', 'border_width' => $dims( 1, 0, 1, 0 ), 'border_color' => '#e7e5df', 'sticky' => 'top', 'sticky_on' => array( 'desktop', 'laptop', 'tablet', 'mobile' ), 'sticky_offset' => 0, 'z_index' => 18, 'html_tag' => 'nav', '_element_id' => 'page-navigation', 'css_classes' => 'dc-air-jumpbar', 'custom_css' => "selector .dc-jumpbar-menu{min-width:0;overflow-x:auto;scrollbar-width:none}selector .dc-jumpbar-menu::-webkit-scrollbar{display:none}selector .elementor-nav-menu{flex-wrap:nowrap;white-space:nowrap}@media(max-width:767px){selector .elementor-nav-menu a{background:#f4f3ef;border-radius:6px;padding:10px 15px;margin:14px 5px}}" ), array( $jump_inner ) );

    /* Costs. */
    $carton_images = array();
    foreach ( array( 'top', 'side', 'front' ) as $face ) {
        $asset = $assets[ 'carton_' . $face ];
        $carton_images[] = $widget( 'cost-carton-' . $face, 'image', array( 'image' => array( 'id' => $asset['id'], 'url' => $asset['url'], 'size' => 'full' ), 'image_size' => 'full', '_css_classes' => 'dc-carton-' . $face ) );
    }
    $carton_images[] = $text( 'cost-carton-width', '80 cm', 'dc-carton-label dc-carton-width', 12 );
    $carton_images[] = $text( 'cost-carton-height', '50 cm', 'dc-carton-label dc-carton-height', 12 );
    $carton_images[] = $text( 'cost-carton-depth', '50 cm', 'dc-carton-label dc-carton-depth', 12 );
    $carton = $container( 'cost-carton', array( 'content_width' => 'full', 'position' => 'relative', 'width' => $size( 250 ), 'width_mobile' => $size( 220 ), 'min_height' => $size( 196 ), 'min_height_mobile' => $size( 150 ), '_flex_grow' => 0, '_flex_align_self' => 'center', 'padding' => $dims( 0, 0, 0, 0 ), 'css_classes' => 'dc-carton' ), $carton_images );
    $calc_data = array( array( '80 × 50 × 50 cm', '200,000 cubic cm' ), array( 'Divided by 6,000', '33.3 kg volumetric' ), array( 'Actual weight on the scales', '10.0 kg' ), array( 'You are charged on', '33.3 kg' ) );
    $calc_rows = array();
    foreach ( $calc_data as $index => $row ) {
        $calc_rows[] = $container( 'cost-calc-row-' . $index, array( 'content_width' => 'full', 'flex_direction' => 'row', 'flex_justify_content' => 'space-between', 'flex_align_items' => 'center', 'flex_gap' => $gap( 24 ), 'border_border' => 'solid', 'border_width' => $dims( $index === 3 ? 2 : 1, 0, 0, 0 ), 'border_color' => $index === 3 ? '#131417' : '#dedbd4', 'padding' => $dims( 16, 0, 16, 0 ), 'padding_mobile' => $dims( 14, 0, 14, 0 ), 'background_hover_background' => 'classic', 'background_hover_color' => '#faf9f6', 'background_hover_transition' => $size( .18, 's' ), 'css_classes' => 'dc-cost-calc-row' . ( 3 === $index ? ' dc-cost-total' : '' ) ), array( $text( 'cost-calc-label-' . $index, $row[0], 'dc-cost-calc-label', 14 ), $heading( 'cost-calc-value-' . $index, $row[1], 'h3', 'dc-cost-calc-value' ) ) );
    }
    $calc = $container( 'cost-calc', array( 'content_width' => 'full', 'flex_direction' => 'column', 'flex_gap' => $gap( 0 ), 'width' => $size( 100, '%' ), 'padding' => $dims( 0, 0, 0, 0 ), 'css_classes' => 'dc-cost-calc' ), $calc_rows );
    $cost_panel = $container( 'cost-panel', array( 'content_width' => 'full', 'flex_direction' => 'row', 'flex_direction_tablet' => 'column', 'flex_justify_content' => 'space-between', 'flex_align_items' => 'center', 'flex_gap' => $gap( 64 ), 'flex_gap_tablet' => $gap( 22 ), 'background_background' => 'classic', 'background_color' => '#f4f3ef', 'border_radius' => $dims( 12, 12, 12, 12 ), 'padding' => $dims( 40, 44, 40, 44 ), 'padding_mobile' => $dims( 24, 20, 24, 20 ), 'css_classes' => 'dc-cost-panel' ), array( $carton, $calc ) );
    $weight_copy = $container( 'cost-weight-copy', array( 'content_width' => 'full', 'flex_direction' => 'column', 'flex_gap' => $gap( 10 ), 'width' => $size( 50, '%' ), 'width_mobile' => $size( 100, '%' ), 'border_border' => 'solid', 'border_width' => $dims( 2, 0, 0, 0 ), 'border_color' => '#131417', 'padding' => $dims( 20, 0, 0, 0 ), 'css_classes' => 'dc-cost-column' ), array( $heading( 'cost-weight-title', 'How chargeable weight works', 'h3' ), $text( 'cost-weight-text', 'Length × width × height in centimetres, divided by 6,000, gives the volumetric weight. A carton 80 × 50 × 50cm weighs 10kg on the scales, but the volume calculation gives 33.3kg, so you are charged on 33.3kg. Couriers divide by 5,000 instead, which is why their quote for the same carton looks different.', '', 13.5 ) ) );
    $included = array( 'Pickup at your supplier', 'Consolidation and unit build', 'Airline uplift', 'Fuel and security surcharges', 'Terminal handling at both ends', 'Customs clearance', 'Duty and GST', 'Delivery to your door' );
    $include_rows = array();
    foreach ( $included as $index => $label ) { $include_rows[] = $container( 'cost-include-' . $index, array( 'content_width' => 'full', 'flex_direction' => 'row', 'flex_align_items' => 'center', 'flex_gap' => $gap( 12 ), 'padding' => $dims( 0, 0, 0, 0 ) ), array( $container( 'cost-tick-' . $index, array( 'content_width' => 'full', 'width' => $size( 12 ), 'width_mobile' => $size( 12 ), 'min_height' => $size( 12 ), '_flex_grow' => 0, '_flex_shrink' => 0, '_flex_align_self' => 'center', 'background_background' => 'classic', 'background_color' => '#fbc925', 'border_radius' => $dims( 3, 3, 3, 3 ), 'padding' => $dims( 0, 0, 0, 0 ), 'css_classes' => 'dc-cost-tick' ) ), $text( 'cost-include-text-' . $index, $label, '', 13.5 ) ) ); }
    $include_rows[] = $text( 'cost-include-note', 'All of it in one written price, not a base rate with a fee stack behind it.', '', 13.5 );
    $include_copy = $container( 'cost-include-copy', array( 'content_width' => 'full', 'flex_direction' => 'column', 'flex_gap' => $gap( 10 ), 'width' => $size( 50, '%' ), 'width_mobile' => $size( 100, '%' ), 'border_border' => 'solid', 'border_width' => $dims( 2, 0, 0, 0 ), 'border_color' => '#131417', 'padding' => $dims( 20, 0, 0, 0 ), 'css_classes' => 'dc-cost-column' ), array_merge( array( $heading( 'cost-include-title', 'What the price includes', 'h3' ) ), $include_rows ) );
    $cost_columns = $container( 'cost-columns', array( 'content_width' => 'full', 'flex_direction' => 'row', 'flex_direction_mobile' => 'column', 'flex_gap' => $gap( 72 ), 'flex_gap_tablet' => $gap( 36 ), 'flex_gap_mobile' => $gap( 26 ), 'padding' => $dims( 0, 0, 0, 0 ), 'css_classes' => 'dc-cost-columns' ), array( $weight_copy, $include_copy ) );
    $cost_css = "selector .dc-carton{position:relative;flex:0 0 250px}selector .dc-carton-top,selector .dc-carton-side,selector .dc-carton-front,selector .dc-carton-label{position:absolute}selector .dc-carton-top{left:40px;top:26px;width:172px}selector .dc-carton-side{left:170px;top:26px;width:42px}selector .dc-carton-front{left:40px;top:60px;width:130px}selector .dc-carton-width{left:65px;top:160px}selector .dc-carton-height{left:0;top:97px}selector .dc-carton-depth{left:220px;top:32px}selector .dc-cost-tick{flex:0 0 12px;width:12px;max-width:12px}@media(max-width:767px){selector .dc-carton{flex-basis:150px;transform:scale(.88);transform-origin:top center}}";
    $costs = $root( 'costs-root', 'costs', 'dc-costs-section', '#ffffff', array( $inner( 'costs-inner', array( $intro( 'costs', 'What it costs.', 'Air freight is charged on whichever is greater: the actual weight, or the space the shipment takes up. The second number is the one that catches people out.' ), $cost_panel, $cost_columns ), 'dc-costs-container', 44 ) ), $cost_css );

    /* Process. */
    $process_asset = $assets['process'];
    $process_image = $widget( 'process-image', 'image', array( 'image' => array( 'id' => $process_asset['id'], 'url' => $process_asset['url'], 'size' => 'full' ), 'image_size' => 'full', 'width' => $size( 100, '%' ), 'image_border_radius' => $dims( 12, 12, 12, 12 ), '_css_classes' => 'dc-process-image' ) );
    $step_data = array(
        array( 'Collection', 'Your cartons are collected from your supplier and brought to the origin consolidation warehouse.' ),
        array( 'Sorting', 'Freight is grouped by destination airport, flight and delivery date, so everything on one unit is going to the same place at the same time.' ),
        array( 'Build', 'The consignments are combined onto a single air cargo pallet or container to use the space. Sharing the aircraft only saves money if the build is tight, so this is where the saving is actually made.' ),
        array( 'Documentation', 'One Master Air Waybill covers the whole unit on the flight. Your shipment sits under it on its own House Air Waybill, which is the document that names you as the consignee.' ),
        array( 'Transport', 'The unit flies to your Australian port as a single consignment on a scheduled commercial service.' ),
        array( 'Deconsolidation', 'The unit is broken down at the arrival hub and your freight is separated back out against its House Air Waybill.' ),
        array( 'Clearance', 'Your declaration is lodged before the aircraft lands, so the goods clear instead of collecting storage.' ),
        array( 'Delivery', 'Your freight leaves on our own truck and is delivered to your door.' ),
    );
    $steps = array();
    foreach ( $step_data as $index => $data ) {
        $mark = $container( 'process-mark-' . $index, array( 'content_width' => 'full', 'width' => $size( 34 ), 'width_mobile' => $size( 28 ), 'min_height' => $size( 34 ), 'min_height_mobile' => $size( 28 ), '_flex_grow' => 0, '_flex_shrink' => 0, '_flex_align_self' => 'flex-start', 'flex_direction' => 'column', 'flex_justify_content' => 'center', 'flex_align_items' => 'center', 'background_background' => 'classic', 'background_color' => '#fbc925', 'border_radius' => $dims( 50, 50, 50, 50, '%' ), 'padding' => $dims( 0, 0, 0, 0 ), 'css_classes' => 'dc-step-mark' ), array( $heading( 'process-number-' . $index, str_pad( (string) ( $index + 1 ), 2, '0', STR_PAD_LEFT ), 'h4', 'dc-step-number' ) ) );
        $body = $container( 'process-body-' . $index, array( 'content_width' => 'full', 'flex_direction' => 'row', 'flex_direction_mobile' => 'column', 'flex_gap' => $gap( 28 ), 'flex_gap_mobile' => $gap( 10 ), 'padding' => $dims( 5, 0, 0, 0 ), 'css_classes' => 'dc-step-body' ), array( $heading( 'process-step-title-' . $index, $data[0], 'h3', 'dc-step-title' ), $text( 'process-step-copy-' . $index, $data[1], 'dc-step-copy', 14.5 ) ) );
        $steps[] = $container( 'process-step-' . $index, array( 'content_width' => 'full', 'flex_direction' => 'row', 'flex_direction_mobile' => 'column', 'flex_gap' => $gap( 24 ), 'flex_gap_mobile' => $gap( 10 ), 'border_border' => 'solid', 'border_width' => $dims( 1, 0, 0, 0 ), 'border_color' => '#dedbd4', 'padding' => $dims( 22, 0, 22, 0 ), 'padding_mobile' => $dims( 20, 0, 20, 0 ), 'background_hover_background' => 'classic', 'background_hover_color' => '#f8f7f3', 'background_hover_transition' => $size( .2, 's' ), 'css_classes' => 'dc-process-step' ), array( $mark, $body ) );
    }
    $step_list = $container( 'process-steps', array( 'content_width' => 'full', 'flex_direction' => 'column', 'flex_gap' => $gap( 0 ), 'padding' => $dims( 0, 0, 0, 0 ), 'css_classes' => 'dc-process-steps' ), $steps );
    $process_css = "selector .dc-process-image{overflow:hidden;border-radius:12px}selector .dc-process-image img{height:260px;object-fit:cover;transition:transform .2s ease}@media(hover:hover) and (pointer:fine){selector .dc-process-image:hover img{transform:scale(1.015)}}selector .dc-step-mark{flex:0 0 34px;width:34px;max-width:34px}selector .dc-step-title{width:230px;flex:0 0 230px}@media(max-width:767px){selector .dc-process-image img{height:200px}selector .dc-step-mark{flex-basis:28px;width:28px;max-width:28px}selector .dc-step-title{width:100%;flex-basis:auto}}";
    $process = $root( 'process-root', 'process', 'dc-process-section', '#f4f3ef', array( $inner( 'process-inner', array( $intro( 'process', 'How it works, step by step.', 'The sequence is the same on every consolidation. We manage each step, and the ones on Australian soil happen in our own facilities.' ), $process_image, $step_list ), 'dc-process-container', 36 ) ), $process_css );

    /* Transit table and mobile cards. */
    $transit_data = array( array( 'China', '3 to 5 days', '5 to 7 days' ), array( 'United States', '4 to 7 days', '7 to 10 days' ), array( 'UK and Europe', '5 to 8 days', '8 to 12 days' ), array( 'New Zealand', '1 to 2 days', '2 to 4 days' ) );
    $desktop_rows = array();
    $header_cells = array(); foreach ( array( 'ORIGIN', 'AIRPORT TO AIRPORT', 'DOOR TO DOOR' ) as $index => $label ) { $header_cells[] = $text( 'transit-head-' . $index, $label, 'dc-transit-label', 10, '#7f8288' ); }
    $desktop_rows[] = $container( 'transit-header', array( 'content_width' => 'full', 'display' => 'grid', 'grid_columns_grid' => array( 'size' => 3, 'unit' => 'fr' ), 'grid_rows_grid' => array( 'size' => 1, 'unit' => 'fr' ), 'border_border' => 'solid', 'border_width' => $dims( 0, 0, 1, 0 ), 'border_color' => '#131417', 'padding' => $dims( 0, 0, 14, 0 ), 'css_classes' => 'dc-transit-row dc-transit-header' ), $header_cells );
    foreach ( $transit_data as $index => $data ) {
        $desktop_rows[] = $container( 'transit-row-' . $index, array( 'content_width' => 'full', 'display' => 'grid', 'grid_columns_grid' => array( 'size' => 3, 'unit' => 'fr' ), 'grid_rows_grid' => array( 'size' => 1, 'unit' => 'fr' ), 'border_border' => 'solid', 'border_width' => $dims( 0, 0, 1, 0 ), 'border_color' => '#dedbd4', 'padding' => $dims( 22, 0, 22, 0 ), 'background_hover_background' => 'classic', 'background_hover_color' => '#faf9f6', 'background_hover_transition' => $size( .18, 's' ), 'css_classes' => 'dc-transit-row' ), array( $text( 'transit-origin-' . $index, '<strong>' . $data[0] . '</strong>', '', 15, '#131417' ), $text( 'transit-air-' . $index, $data[1], '', 15 ), $text( 'transit-door-' . $index, $data[2], '', 15 ) ) );
    }
    $desktop_table = $container( 'transit-table', array( 'content_width' => 'full', 'flex_direction' => 'column', 'flex_gap' => $gap( 0 ), 'hide_mobile' => 'hidden-mobile', 'padding' => $dims( 0, 0, 0, 0 ), 'css_classes' => 'dc-transit-table' ), $desktop_rows );
    $mobile_cards = array();
    foreach ( $transit_data as $index => $data ) {
        $meta = array();
        foreach ( array( array( 'AIRPORT TO AIRPORT', $data[1] ), array( 'DOOR TO DOOR', $data[2] ) ) as $meta_index => $pair ) { $meta[] = $container( 'transit-card-meta-' . $index . '-' . $meta_index, array( 'content_width' => 'full', 'flex_direction' => 'column', 'flex_gap' => $gap( 3 ), 'width' => $size( 50, '%' ), '_flex_grow' => 0, '_flex_align_self' => 'flex-start', 'padding' => $dims( 0, 0, 0, 0 ), 'css_classes' => 'dc-transit-meta-group' ), array( $text( 'transit-card-label-' . $index . '-' . $meta_index, $pair[0], 'dc-transit-label', 9, '#8e9197' ), $text( 'transit-card-value-' . $index . '-' . $meta_index, $pair[1], '', 13.5 ) ) ); }
        $mobile_cards[] = $container( 'transit-card-' . $index, array( 'content_width' => 'full', 'flex_direction' => 'column', 'flex_gap' => $gap( 8 ), 'border_border' => 'solid', 'border_width' => $dims( 1, 0, 0, 0 ), 'border_color' => '#dedbd4', 'padding' => $dims( 16, 0, 16, 0 ), 'css_classes' => 'dc-transit-card' ), array( $heading( 'transit-card-title-' . $index, $data[0], 'h3' ), $container( 'transit-card-meta-row-' . $index, array( 'content_width' => 'full', 'flex_direction' => 'row', 'flex_align_items' => 'flex-start', 'flex_gap' => $gap( 24 ), 'padding' => $dims( 0, 0, 0, 0 ), 'css_classes' => 'dc-transit-meta-row' ), $meta ) ) );
    }
    $mobile_table = $container( 'transit-cards', array( 'content_width' => 'full', 'flex_direction' => 'column', 'flex_gap' => $gap( 0 ), 'hide_desktop' => 'hidden-desktop', 'hide_laptop' => 'hidden-laptop', 'hide_tablet' => 'hidden-tablet', 'padding' => $dims( 0, 0, 0, 0 ), 'css_classes' => 'dc-transit-cards' ), $mobile_cards );
    $transit_css = "selector .dc-transit-row{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));align-items:center}selector .dc-transit-row>.elementor-element{min-width:0}@media(max-width:767px){selector .dc-transit-row{display:none}selector .dc-transit-meta-group{flex:1 1 0;width:auto;max-width:none;min-width:0}}";
    $transit = $root( 'transit-root', 'transit', 'dc-transit-section', '#ffffff', array( $inner( 'transit-inner', array( $intro( 'transit', 'How long it takes.', 'Ranges, not promises. Weather, capacity and customs all move them.' ), $desktop_table, $mobile_table ), 'dc-transit-container', 40 ) ), $transit_css );

    /* FAQ. */
    $faq_items = array(
        array( 'tab_title' => 'How long does air consolidation take from China?', 'tab_content' => '<p>The page gives a typical range of 3 to 5 days airport to airport and 5 to 7 days door to door from China. These are ranges, not promises.</p>' ),
        array( 'tab_title' => 'Is consolidation cheaper than a direct uplift?', 'tab_content' => '<p>In the comparison on this page, air consolidation sits in the middle on relative cost while direct air uplift is high. If the shipment is close to the line, the team prices both and recommends the cheaper option.</p>' ),
        array( 'tab_title' => 'What is the cut-off for a booking?', 'tab_content' => '<p>The High Fidelity source does not provide a published cut-off time for this question yet. Use the enquiry form and the team can confirm the applicable origin and uplift.</p>' ),
        array( 'tab_title' => 'How is chargeable weight calculated?', 'tab_content' => '<p>Length × width × height in centimetres, divided by 6,000, gives volumetric weight. Air freight is charged on whichever is greater: actual weight or volumetric weight.</p>' ),
    );
    foreach ( $faq_items as $index => &$faq_item ) { $faq_item['_id'] = substr( md5( 'faq-' . $index ), 0, 7 ); } unset( $faq_item );
    $faq_intro = $container( 'faq-intro', array( 'content_width' => 'full', 'flex_direction' => 'column', 'flex_gap' => $gap( 14 ), 'width' => $size( 31, '%' ), 'width_tablet' => $size( 100, '%' ), 'padding' => $dims( 0, 0, 0, 0 ), 'css_classes' => 'dc-faq-intro' ), array( $heading( 'faq-title', 'Air consolidation questions.', 'h2', 'dc-section-title' ), $text( 'faq-lead', 'If yours is not here, a senior person will answer the phone.', '', 14 ) ) );
    $accordion = $widget( 'faq-accordion', 'accordion', array( 'tabs' => $faq_items, 'selected_icon' => array( 'value' => 'fas fa-plus', 'library' => 'fa-solid' ), 'selected_active_icon' => array( 'value' => 'fas fa-times', 'library' => 'fa-solid' ), 'title_background' => 'transparent', 'title_color' => '#131417', 'title_active_color' => '#131417', 'title_typography_typography' => 'custom', 'title_typography_font_family' => 'Poppins', 'title_typography_font_size' => $size( 15.5 ), 'title_typography_font_weight' => '500', 'content_background_color' => 'transparent', 'content_color' => '#5a5d63', 'content_typography_typography' => 'custom', 'content_typography_font_family' => 'Poppins', 'content_typography_font_size' => $size( 14 ), 'border_color' => '#dedbd4', 'border_width' => $size( 1 ), '_css_classes' => 'dc-faq-accordion' ) );
    $faq_layout = $container( 'faq-layout', array( 'content_width' => 'full', 'flex_direction' => 'row', 'flex_direction_tablet' => 'column', 'flex_gap' => $gap( 88 ), 'flex_gap_tablet' => $gap( 42 ), 'flex_gap_mobile' => $gap( 26 ), 'padding' => $dims( 0, 0, 0, 0 ), 'css_classes' => 'dc-faq-layout' ), array( $faq_intro, $container( 'faq-list', array( 'content_width' => 'full', 'width' => $size( 69, '%' ), 'width_tablet' => $size( 100, '%' ), 'padding' => $dims( 0, 0, 0, 0 ), 'css_classes' => 'dc-faq-list' ), array( $accordion ) ) ) );
    $faq_css = "@media(hover:hover) and (pointer:fine){selector .elementor-accordion-item:hover .elementor-tab-title{background:rgba(19,20,23,.025)}selector .elementor-accordion-item:hover .elementor-accordion-icon{transform:rotate(90deg)}}selector .elementor-tab-title,selector .elementor-accordion-icon{transition:color .18s,background-color .18s,transform .18s}";
    $faq = $root( 'faq-root', 'questions', 'dc-faq-section', '#f4f3ef', array( $inner( 'faq-inner', array( $faq_layout ), 'dc-faq-container', 0 ) ), $faq_css );

    /* Enquiry. */
    $trust_items = array();
    foreach ( array( array( 'We reply the same business day', 'A senior person, across your enquiry.' ), array( 'You get one written price', 'Every fee included. Take it or keep it as a benchmark.' ) ) as $index => $data ) {
        $trust_items[] = $container( 'enquiry-trust-' . $index, array( 'content_width' => 'full', 'flex_direction' => 'column', 'flex_gap' => $gap( 6 ), 'border_border' => 'solid', 'border_width' => $dims( 1, 0, 0, 0 ), 'border_color' => '#dedbd4', 'padding' => $dims( 16, 0, 16, 0 ), 'padding_mobile' => $dims( 14, 0, 14, 0 ), 'css_classes' => 'dc-enquiry-trust-item' ), array( $heading( 'enquiry-trust-title-' . $index, $data[0], 'h3' ), $text( 'enquiry-trust-copy-' . $index, $data[1], '', 14 ) ) );
    }
    $enquiry_copy = $container( 'enquiry-copy', array( 'content_width' => 'full', 'flex_direction' => 'column', 'flex_gap' => $gap( 16 ), 'width' => $size( 50, '%' ), 'width_tablet' => $size( 100, '%' ), 'padding' => $dims( 0, 0, 0, 0 ), 'css_classes' => 'dc-enquiry-copy' ), array_merge( array( $heading( 'enquiry-title', 'Talk to the team about air consolidation.', 'h2', 'dc-section-title' ), $text( 'enquiry-lead', 'A senior person replies the same business day, with a real answer.', 'dc-section-lead', 15 ) ), $trust_items ) );
    $form_fields = array(
        array( '_id' => 'name', 'custom_id' => 'name', 'field_type' => 'text', 'field_label' => 'Name', 'placeholder' => 'John Doe', 'required' => 'true', 'width' => '100' ),
        array( '_id' => 'email', 'custom_id' => 'email', 'field_type' => 'email', 'field_label' => 'Work email', 'placeholder' => 'John.Doe@company.com.au', 'required' => 'true', 'width' => '100' ),
        array( '_id' => 'phone', 'custom_id' => 'phone', 'field_type' => 'tel', 'field_label' => 'Phone', 'placeholder' => '04xx xxx xxx', 'required' => 'true', 'width' => '100' ),
        array( '_id' => 'import', 'custom_id' => 'import', 'field_type' => 'text', 'field_label' => 'What are you importing?', 'placeholder' => 'Machinery parts from Shenzhen, monthly', 'required' => 'true', 'width' => '100' ),
        array( '_id' => 'note', 'field_type' => 'html', 'field_html' => '<p>A person replies. No quote-bot, no ticket queue.</p>', 'width' => '100' ),
    );
    $enquiry_form = $widget( 'enquiry-form', 'form', array( 'form_name' => 'Air Consolidation Enquiry', 'form_fields' => $form_fields, 'button_text' => 'Talk to our team', 'show_labels' => 'yes', 'mark_required' => '', 'submit_actions' => array( 'email' ), 'email_to' => get_option( 'admin_email' ), 'email_subject' => 'Air consolidation enquiry', 'input_size' => 'md', 'button_size' => 'md', 'button_width' => '100', 'column_gap' => $size( 14 ), 'row_gap' => $size( 14 ), 'label_color' => '#131417', 'label_typography_typography' => 'custom', 'label_typography_font_family' => 'Poppins', 'label_typography_font_size' => $size( 12 ), 'label_typography_font_weight' => '600', 'field_text_color' => '#131417', 'field_background_color' => '#ffffff', 'field_border_color' => '#dddbd5', 'field_border_width' => $dims( 1.5, 1.5, 1.5, 1.5 ), 'field_border_radius' => $dims( 6, 6, 6, 6 ), 'field_typography_typography' => 'custom', 'field_typography_font_family' => 'Poppins', 'field_typography_font_size' => $size( 13.5 ), 'button_background_color' => '#fbc925', 'button_text_color' => '#131417', 'button_background_hover_color' => '#f7d85f', 'button_hover_color' => '#131417', 'button_hover_animation' => 'float', 'button_border_radius' => $dims( 6, 6, 6, 6 ), 'button_text_padding' => $dims( 14, 26, 14, 26 ), 'button_typography_typography' => 'custom', 'button_typography_font_family' => 'Poppins', 'button_typography_font_size' => $size( 13.5 ), 'button_typography_font_weight' => '600', '_css_classes' => 'dc-enquiry-form' ) );
    $form_card = $container( 'enquiry-form-card', array( 'content_width' => 'full', 'width' => $size( 50, '%' ), 'width_tablet' => $size( 100, '%' ), 'background_background' => 'classic', 'background_color' => '#f4f3ef', 'border_radius' => $dims( 12, 12, 12, 12 ), 'padding' => $dims( 34, 34, 34, 34 ), 'padding_mobile' => $dims( 26, 22, 26, 22 ), 'css_classes' => 'dc-enquiry-form-card' ), array( $enquiry_form ) );
    $enquiry_layout = $container( 'enquiry-layout', array( 'content_width' => 'full', 'flex_direction' => 'row', 'flex_direction_tablet' => 'column', 'flex_gap' => $gap( 88 ), 'flex_gap_tablet' => $gap( 42 ), 'flex_gap_mobile' => $gap( 26 ), 'padding' => $dims( 0, 0, 0, 0 ), 'css_classes' => 'dc-enquiry-layout' ), array( $enquiry_copy, $form_card ) );
    $enquiry = $root( 'enquiry-root', 'enquiry', 'dc-enquiry-section', '#ffffff', array( $inner( 'enquiry-inner', array( $enquiry_layout ), 'dc-enquiry-container', 0 ) ) );

    return array( $jumpbar, $costs, $process, $transit, $faq, $enquiry );
}

if ( defined( 'WP_CLI' ) && WP_CLI && ! defined( 'DESIGN_CORE_AIR_PAGE_COMPLETION_BLUEPRINT_ONLY' ) ) {
    if ( ! current_user_can( 'manage_options' ) ) { throw new RuntimeException( 'Administrator capability is required.' ); }
    $attachment = static function ( $slug ) { $posts = get_posts( array( 'post_type' => 'attachment', 'post_status' => 'inherit', 'name' => $slug, 'numberposts' => 2 ) ); if ( 1 !== count( $posts ) ) { throw new RuntimeException( 'Missing unique asset ' . $slug ); } return array( 'id' => (int) $posts[0]->ID, 'url' => wp_get_attachment_url( $posts[0]->ID ) ); };
    $menu = wp_get_nav_menu_object( 'design-core-air-section-navigation' );
    if ( ! $menu ) { $menu_id = wp_create_nav_menu( 'Design Core Air Section Navigation' ); if ( is_wp_error( $menu_id ) ) { throw new RuntimeException( $menu_id->get_error_message() ); } $menu = wp_get_nav_menu_object( $menu_id ); }
    foreach ( wp_get_nav_menu_items( $menu->term_id, array( 'post_status' => 'any' ) ) ?: array() as $old ) { wp_delete_post( $old->ID, true ); }
    foreach ( array( array( 'What it is', '#what' ), array( 'Why use it', '#why' ), array( 'Compare', '#compare' ), array( 'What it costs', '#costs' ), array( 'How it works', '#process' ), array( 'Questions', '#questions' ) ) as $item ) { $saved = wp_update_nav_menu_item( $menu->term_id, 0, array( 'menu-item-title' => $item[0], 'menu-item-url' => $item[1], 'menu-item-status' => 'publish', 'menu-item-type' => 'custom' ) ); if ( is_wp_error( $saved ) ) { throw new RuntimeException( $saved->get_error_message() ); } }

    $elements = design_core_air_page_completion_elements( array( 'carton_top' => $attachment( 'intercargo-carton-top' ), 'carton_side' => $attachment( 'intercargo-carton-side' ), 'carton_front' => $attachment( 'intercargo-carton-front' ), 'process' => $attachment( 'intercargo-process' ) ) );
    $owned = array( 'dc-air-jumpbar', 'dc-costs-section', 'dc-process-section', 'dc-transit-section', 'dc-faq-section', 'dc-enquiry-section' );
    $new_by_class = array(); foreach ( $elements as $element ) { foreach ( $owned as $class ) { if ( false !== strpos( ' ' . ( $element['settings']['css_classes'] ?? '' ) . ' ', ' ' . $class . ' ' ) ) { $new_by_class[ $class ] = $element; } } }
    $stored = json_decode( (string) get_post_meta( 2, '_elementor_data', true ), true ); if ( ! is_array( $stored ) ) { throw new RuntimeException( 'Page ID 2 data is invalid.' ); }
    $existing = array(); $existing_hashes = array();
    foreach ( $stored as $element ) { $classes = ' ' . (string) ( $element['settings']['css_classes'] ?? '' ) . ' '; $is_owned = false; foreach ( $owned as $class ) { if ( false !== strpos( $classes, ' ' . $class . ' ' ) ) { $is_owned = true; break; } } if ( $is_owned ) { continue; } foreach ( array( 'dc-air-hero', 'dc-what-section', 'dc-why-section', 'dc-compare-section', 'dc-conversion-section' ) as $class ) { if ( false !== strpos( $classes, ' ' . $class . ' ' ) ) { $existing[ $class ] = $element; $existing_hashes[ $class ] = hash( 'sha256', wp_json_encode( $element ) ); } } }
    foreach ( array( 'dc-air-hero', 'dc-what-section', 'dc-why-section', 'dc-compare-section', 'dc-conversion-section' ) as $required ) { if ( empty( $existing[ $required ] ) ) { throw new RuntimeException( 'Required existing root missing: ' . $required ); } }
    $next = array( $existing['dc-air-hero'], $new_by_class['dc-air-jumpbar'], $existing['dc-what-section'], $existing['dc-why-section'], $existing['dc-compare-section'], $existing['dc-conversion-section'], $new_by_class['dc-costs-section'], $new_by_class['dc-process-section'], $new_by_class['dc-transit-section'], $new_by_class['dc-faq-section'], $new_by_class['dc-enquiry-section'] );
    $adapter = new Design_Core_Elementor_V3_Adapter(); $saved = $adapter->save_page( 2, $next, array( 'template' => 'elementor_header_footer', 'hide_title' => 'yes' ) ); if ( is_wp_error( $saved ) ) { throw new RuntimeException( $saved->get_error_message() ); }
    $reloaded = $adapter->reload( 2 ); if ( 11 !== count( $reloaded ) ) { throw new RuntimeException( 'Page completion did not persist exactly 11 roots.' ); }
    foreach ( $reloaded as $element ) { $classes = ' ' . (string) ( $element['settings']['css_classes'] ?? '' ) . ' '; foreach ( $existing_hashes as $class => $hash ) { if ( false !== strpos( $classes, ' ' . $class . ' ' ) && $hash !== hash( 'sha256', wp_json_encode( $element ) ) ) { throw new RuntimeException( 'Existing root changed: ' . $class ); } } }
    if ( class_exists( '\Elementor\Plugin' ) ) { \Elementor\Plugin::$instance->files_manager->clear_cache(); }
    $rendered = $adapter->render( 2 ); foreach ( array( 'What it costs.', 'How it works, step by step.', 'How long it takes.', 'Air consolidation questions.', 'Talk to the team about air consolidation.' ) as $copy ) { if ( false === strpos( $rendered, $copy ) ) { throw new RuntimeException( 'Rendered page is missing: ' . $copy ); } }
    WP_CLI::print_value( array( 'status' => 'pass', 'post_id' => 2, 'root_count' => count( $reloaded ), 'existing_roots_preserved' => count( $existing_hashes ), 'new_roots' => count( $elements ), 'rendered_bytes' => strlen( $rendered ), 'page_posts_created' => 0 ) );
}
