<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }

function design_core_air_modernize_hero_what( array $elements ) {
    $size = static function ( $value, $unit = 'px' ) { return array( 'size' => $value, 'unit' => $unit, 'sizes' => array() ); };
    $dims = static function ( $top, $right, $bottom, $left, $unit = 'px' ) { return array( 'top' => $top, 'right' => $right, 'bottom' => $bottom, 'left' => $left, 'unit' => $unit, 'isLinked' => false ); };
    $gap = static function ( $value ) { return array( 'column' => (string) $value, 'row' => (string) $value, 'isLinked' => true, 'unit' => 'px', 'size' => $value ); };
    $tokens = static function ( $element ) { $settings=(array)($element['settings']??array());return preg_split('/\s+/',trim((string)($settings['css_classes']??$settings['_css_classes']??'')))?:array(); };
    $has = static function ( $element, $class ) use ( $tokens ) { return in_array( $class, $tokens( $element ), true ); };
    $merge = static function ( &$element, array $settings ) { $element['settings'] = array_replace( (array) ( $element['settings'] ?? array() ), $settings ); };
    $form = static function () use ( $size, $dims ) { return array(
        'id' => substr( md5( 'dc-air-modern-hero-form' ), 0, 8 ), 'elType' => 'widget', 'widgetType' => 'form', 'isInner' => false, 'elements' => array(),
        'settings' => array(
            'form_name' => 'Air Consolidation Starter', 'form_fields' => array( array( '_id'=>'import','custom_id'=>'import','field_type'=>'text','field_label'=>'What are you importing?','placeholder'=>'Machinery parts from Shenzhen, monthly','required'=>'','width'=>'66','width_tablet'=>'66','width_mobile'=>'100' ) ),
            'button_text' => 'Talk to our team', 'show_labels' => '', 'mark_required' => '', 'submit_actions' => array(), 'input_size' => 'md', 'button_width' => '33', 'button_width_tablet' => '33', 'button_width_mobile' => '100',
            'column_gap' => $size( 8 ), 'row_gap' => $size( 8 ), 'field_text_color' => '#131417', 'field_background_color' => '#f2f1ef', 'field_border_color' => '#dddbd5', 'field_border_width' => $dims( 1, 1, 1, 1 ), 'field_border_radius' => $dims( 6, 6, 6, 6 ),
            'field_typography_typography' => 'custom', 'field_typography_font_family' => 'Poppins', 'field_typography_font_size' => $size( 13.5 ), 'field_typography_font_weight' => '400',
            'button_background_color' => '#fbc925', 'button_text_color' => '#131417', 'button_background_hover_color' => '#f2bd06', 'button_hover_color' => '#131417', 'button_hover_animation' => 'float', 'button_border_radius' => $dims( 6, 6, 6, 6 ), 'button_text_padding' => $dims( 14, 26, 14, 26 ),
            'button_typography_typography' => 'custom', 'button_typography_font_family' => 'Poppins', 'button_typography_font_size' => $size( 13.5 ), 'button_typography_font_weight' => '600', '_css_classes' => 'dc-hero-native-form',
        ),
    ); };

    $hero_layout_css = "selector{position:relative;overflow:visible}selector .dc-hero-bg,selector .dc-hero-bg>.e-con-inner,selector .dc-hero-image,selector .dc-hero-image .elementor-widget-container{height:300px}selector .dc-hero-image img{display:block;width:100%;height:300px;object-fit:cover;transition:transform .2s ease}selector .dc-hero-crumb{position:absolute;z-index:2;top:24px;left:max(64px,calc((100vw - var(--container-max-width))/2 + 64px));width:auto}selector .dc-hero-card{position:absolute;z-index:3;top:182px;left:50%;transform:translateX(-50%)}@media(max-width:1024px){selector .dc-hero-bg,selector .dc-hero-bg>.e-con-inner,selector .dc-hero-image,selector .dc-hero-image .elementor-widget-container{height:270px}selector .dc-hero-image img{height:270px}selector .dc-hero-card{top:160px}selector .dc-hero-crumb{top:18px;left:32px}}@media(max-width:767px){selector .dc-hero-bg,selector .dc-hero-bg>.e-con-inner,selector .dc-hero-image,selector .dc-hero-image .elementor-widget-container{height:230px}selector .dc-hero-image img{height:230px}selector .dc-hero-card{top:134px}selector .dc-hero-crumb{top:18px;left:16px;width:calc(100% - 32px)}selector .dc-hero-crumbline span:nth-child(-n+4){display:none}}";
    $what_art_css = "selector .dc-diagram-art{height:132px;min-height:132px;overflow:hidden}selector .dc-stack-art,selector .dc-split-art,selector .dc-unit-art{position:relative}selector .dc-art-box{position:absolute;left:calc(50% - 28px);top:16px;width:56px;height:26px;min-height:0}selector .dc-art-box-2{top:52px}selector .dc-art-box-3{top:88px}selector .dc-unit-shell{position:relative;width:114px;height:108px;min-height:0}selector .dc-unit-shell .dc-art-box{left:13px;width:86px;height:24px;top:12px}selector .dc-unit-shell .dc-art-box-2{top:42px}selector .dc-unit-shell .dc-art-box-3{top:72px}selector .dc-split-art .dc-art-box{left:calc(50% - 53px);opacity:.45}selector .dc-split-art .dc-art-box-1{left:calc(50% - 2px);opacity:1}@media(max-width:767px){selector .dc-diagram-item{flex-wrap:nowrap}selector .dc-diagram-copy{flex:1 1 0;width:auto;min-width:0}selector .dc-diagram-art{height:88px;min-height:88px;flex:0 0 96px}selector .dc-art-box{width:38px;height:18px}selector .dc-stack-art .dc-art-box{left:57px;top:32px}selector .dc-stack-art .dc-art-box-2{top:56px}selector .dc-stack-art .dc-art-box-3{top:80px}selector .dc-unit-shell{width:77px;height:73px}selector .dc-unit-shell .dc-art-box{left:9px;width:58px;height:16px;top:8px}selector .dc-unit-shell .dc-art-box-2{top:28px}selector .dc-unit-shell .dc-art-box-3{top:48px}selector .dc-split-art .dc-art-box{left:40px;top:32px}selector .dc-split-art .dc-art-box-1{left:74px}selector .dc-split-art .dc-art-box-2{top:56px}selector .dc-split-art .dc-art-box-3{top:80px}}@media(min-width:721px) and (max-width:767px){selector .dc-what-diagram{flex-direction:row;flex-wrap:wrap}selector .dc-diagram-item{flex:0 0 50%;width:50%;flex-direction:column}selector .dc-diagram-copy{width:100%}}";

    $walk = function ( &$nodes ) use ( &$walk, $has, $merge, $size, $dims, $gap, $form, $hero_layout_css, $what_art_css ) {
        foreach ( $nodes as &$element ) {
            $current_classes = trim( (string) ( $element['settings']['css_classes'] ?? $element['settings']['_css_classes'] ?? '' ) );
            if ( $has( $element, 'dc-air-hero' ) ) { $existing=(string)($element['settings']['custom_css']??'');$hover='';if(preg_match('/\/\* DC_HOVER_BEGIN \*\/.*?\/\* DC_HOVER_END \*\//s',$existing,$m)){$hover="\n".$m[0];}$element['settings']=array('content_width'=>'full','flex_direction'=>'column','flex_gap'=>$gap(0),'width'=>$size(100,'%'),'min_height'=>$size(460),'min_height_tablet'=>$size(543),'min_height_mobile'=>$size(541),'padding'=>$dims(0,0,0,0),'background_background'=>'classic','background_color'=>'#ffffff','html_tag'=>'section','css_classes'=>'dc-air-hero','custom_css'=>$hero_layout_css.$hover); }
            elseif ( $has( $element, 'dc-hero-bg' ) ) { $element['settings']=array('content_width'=>'full','flex_direction'=>'column','flex_gap'=>$gap(0),'min_height'=>$size(300),'min_height_tablet'=>$size(270),'min_height_mobile'=>$size(230),'padding'=>$dims(0,0,0,0),'overflow'=>'hidden','css_classes'=>'dc-hero-bg'); }
            elseif ( $has( $element, 'dc-hero-image' ) ) { $merge($element,array('width'=>$size(100,'%'),'object-fit'=>'cover','object-position'=>'center center','_css_classes'=>'dc-hero-image')); }
            elseif ( $has( $element, 'dc-hero-card' ) ) { $element['settings']=array('content_width'=>'boxed','flex_direction'=>'column','flex_gap'=>$gap(0),'padding'=>$dims(42,56,44,56),'padding_tablet'=>$dims(34,34,34,34),'padding_mobile'=>$dims(26,22,28,22),'background_background'=>'classic','background_color'=>'#ffffff','border_border'=>'solid','border_width'=>$dims(1,1,1,1),'border_color'=>'#e2e0db','border_radius'=>$dims(12,12,12,12),'box_shadow_box_shadow_type'=>'yes','box_shadow_box_shadow'=>array('horizontal'=>0,'vertical'=>10,'blur'=>34,'spread'=>0,'color'=>'rgba(19,20,23,.04)'),'css_classes'=>'dc-hero-card dc-global-container'); }
            elseif ( $has( $element, 'dc-hero-grid' ) ) { $element['settings']=array('content_width'=>'full','flex_direction'=>'row','flex_direction_tablet'=>'column','flex_gap'=>$gap(56),'flex_gap_tablet'=>$gap(28),'flex_gap_mobile'=>$gap(22),'flex_align_items'=>'flex-end','flex_align_items_tablet'=>'stretch','padding'=>$dims(0,0,0,0),'css_classes'=>'dc-hero-grid'); }
            elseif ( $has( $element, 'dc-hero-copy' ) ) { $element['settings']=array('content_width'=>'full','flex_direction'=>'column','flex_gap'=>$gap(16),'flex_gap_mobile'=>$gap(12),'width'=>$size(52,'%'),'width_tablet'=>$size(100,'%'),'padding'=>$dims(0,0,0,0),'css_classes'=>'dc-hero-copy'); }
            elseif ( $has( $element, 'dc-hero-starter' ) ) { $element['settings']=array('content_width'=>'full','flex_direction'=>'column','flex_gap'=>$gap(12),'width'=>$size(45,'%'),'width_tablet'=>$size(100,'%'),'padding'=>$dims(0,0,0,0),'css_classes'=>'dc-hero-starter'); }
            elseif ( $has( $element, 'dc-hero-formrow' ) ) { $element['settings']=array('content_width'=>'full','flex_direction'=>'column','flex_gap'=>$gap(8),'padding'=>$dims(0,0,0,0),'css_classes'=>'dc-hero-formrow');$element['elements']=array($form()); }
            elseif ( $has( $element, 'dc-hero-title' ) ) { $merge($element,array('title_color'=>'#131417','typography_typography'=>'custom','typography_font_family'=>'Geist','typography_font_size'=>$size(44),'typography_font_size_tablet'=>$size(36),'typography_font_size_mobile'=>$size(30),'typography_font_weight'=>'600','typography_line_height'=>$size(1.02,'em'),'typography_letter_spacing'=>$size(-1.232),'_css_classes'=>'dc-hero-title')); }
            elseif ( $has( $element, 'dc-hero-lead' ) ) { $merge($element,array('text_color'=>'#5b5955','typography_typography'=>'custom','typography_font_family'=>'Poppins','typography_font_size'=>$size(17),'typography_font_size_mobile'=>$size(14.5),'typography_font_weight'=>'400','typography_line_height'=>$size(1.68,'em'),'_css_classes'=>'dc-hero-lead')); }
            elseif ( $has( $element, 'dc-hero-question' ) ) { $merge($element,array('title_color'=>'#131417','typography_typography'=>'custom','typography_font_family'=>'Geist','typography_font_size'=>$size(21),'typography_font_size_mobile'=>$size(19),'typography_font_weight'=>'600','typography_line_height'=>$size(1.2,'em'),'typography_letter_spacing'=>$size(-.315),'_css_classes'=>'dc-hero-question')); }
            elseif ( $has( $element, 'dc-hero-note' ) ) { $merge($element,array('text_color'=>'#999793','typography_typography'=>'custom','typography_font_family'=>'Poppins','typography_font_size'=>$size(12.5),'typography_font_size_mobile'=>$size(11.5),'typography_line_height'=>$size(1.5,'em'),'_css_classes'=>'dc-hero-note')); }
            elseif ( $has( $element, 'dc-what-section' ) ) { $existing=(string)($element['settings']['custom_css']??'');$hover='';if(preg_match('/\/\* DC_HOVER_BEGIN \*\/.*?\/\* DC_HOVER_END \*\//s',$existing,$m)){$hover="\n".$m[0];}$element['settings']=array('content_width'=>'full','flex_direction'=>'column','flex_gap'=>$gap(0),'padding'=>$dims(110,0,110,0),'padding_tablet'=>$dims(76,0,76,0),'padding_mobile'=>$dims(64,0,64,0),'background_background'=>'classic','background_color'=>'#ffffff','html_tag'=>'section','_element_id'=>'what','css_classes'=>'dc-what-section','custom_css'=>$what_art_css.$hover); }
            elseif ( $has( $element, 'dc-what-container' ) ) {
                $element['settings']=array('content_width'=>'boxed','flex_direction'=>'column','flex_gap'=>$gap(44),'flex_gap_mobile'=>$gap(32),'padding'=>$dims(0,0,0,0),'css_classes'=>'dc-what-container dc-global-container');
                $already_grouped = ! empty( $element['elements'][0] ) && $has( $element['elements'][0], 'dc-what-intro' );
                if ( ! $already_grouped && count( $element['elements'] ?? array() ) >= 3 ) {
                    $intro_children = array_splice( $element['elements'], 0, 2 );
                    array_unshift( $element['elements'], array( 'id'=>substr(md5('dc-what-intro'),0,8),'elType'=>'container','isInner'=>false,'settings'=>array('content_width'=>'full','flex_direction'=>'column','flex_gap'=>$gap(16),'flex_gap_mobile'=>$gap(14),'padding'=>$dims(0,0,0,0),'css_classes'=>'dc-what-intro'),'elements'=>$intro_children ) );
                }
            }
            elseif ( $has( $element, 'dc-what-diagram' ) ) { $element['settings']=array('content_width'=>'full','flex_direction'=>'row','flex_wrap_tablet'=>'wrap','flex_direction_mobile'=>'column','flex_gap'=>$gap(0),'background_background'=>'classic','background_color'=>'#f4f3f0','border_radius'=>$dims(12,12,12,12),'padding'=>$dims(44,40,44,40),'padding_tablet'=>$dims(20,20,20,20),'padding_mobile'=>$dims(8,20,8,20),'css_classes'=>'dc-what-diagram'); }
            elseif ( $has( $element, 'dc-diagram-item' ) ) { $element['settings']=array('content_width'=>'full','flex_direction'=>'column','flex_direction_mobile'=>'row','flex_align_items'=>'center','flex_align_items_mobile'=>'center','flex_gap'=>$gap(0),'flex_gap_mobile'=>$gap(18),'width'=>$size(25,'%'),'width_tablet'=>$size(50,'%'),'width_mobile'=>$size(100,'%'),'padding'=>$dims(0,10,0,10),'padding_tablet'=>$dims(24,24,24,24),'padding_mobile'=>$dims(18,0,18,0),'css_classes'=>$current_classes); }
            elseif ( $has( $element, 'dc-diagram-arrow' ) ) { $merge($element,array('width'=>$size(22),'hide_tablet'=>'hidden-tablet','hide_mobile'=>'hidden-mobile','_css_classes'=>'dc-diagram-arrow')); }
            elseif ( $has( $element, 'dc-diagram-art' ) ) { $element['settings']=array('content_width'=>'full','flex_direction'=>'column','flex_justify_content'=>'center','flex_align_items'=>'center','width'=>$size(100,'%'),'min_height'=>$size(132),'width_mobile'=>$size(96),'min_height_mobile'=>$size(88),'padding'=>$dims(0,0,0,0),'css_classes'=>$current_classes); }
            elseif ( $has( $element, 'dc-diagram-copy' ) ) { $element['settings']=array('content_width'=>'full','flex_direction'=>'column','flex_gap'=>$gap(8),'width'=>$size(100,'%'),'padding'=>$dims(0,0,0,0),'css_classes'=>'dc-diagram-copy'); }
            elseif ( $has( $element, 'dc-diagram-heading' ) ) { $merge($element,array('title_color'=>'#131417','typography_typography'=>'custom','typography_font_family'=>'Geist','typography_font_size'=>$size(16),'typography_font_size_mobile'=>$size(15),'typography_font_weight'=>'600','typography_line_height'=>$size(1.3,'em'),'typography_letter_spacing'=>$size(-.5),'_css_classes'=>'dc-diagram-heading')); }
            elseif ( $has( $element, 'dc-diagram-text' ) ) { $merge($element,array('text_color'=>'#5b5955','typography_typography'=>'custom','typography_font_family'=>'Poppins','typography_font_size'=>$size(12.5),'typography_font_weight'=>'400','typography_line_height'=>$size(1.6,'em'),'_css_classes'=>'dc-diagram-text')); }
            $walk( $element['elements'] );
        }
        unset( $element );
    };
    $walk( $elements );
    return $elements;
}

if ( defined( 'WP_CLI' ) && WP_CLI && ! defined( 'DESIGN_CORE_AIR_HERO_WHAT_BLUEPRINT_ONLY' ) ) {
    if ( ! current_user_can( 'manage_options' ) ) { throw new RuntimeException( 'Administrator capability is required.' ); }
    $post_id=2;$stored=json_decode((string)get_post_meta($post_id,'_elementor_data',true),true);if(!is_array($stored)){throw new RuntimeException('Page ID 2 data is invalid.');}
    $modern=design_core_air_modernize_hero_what($stored);$adapter=new Design_Core_Elementor_V3_Adapter();$saved=$adapter->save_page($post_id,$modern,array('template'=>'elementor_header_footer','hide_title'=>'yes'));if(is_wp_error($saved)){throw new RuntimeException($saved->get_error_message());}
    $reloaded=$adapter->reload($post_id);$html=0;$stylesheet=0;$forms=0;$walk=function($els)use(&$walk,&$html,&$stylesheet,&$forms){foreach((array)$els as $e){if(($e['widgetType']??'')==='html'){$html++;if(stripos((string)($e['settings']['html']??''),'<style')!==false)$stylesheet++;}if(($e['widgetType']??'')==='form')$forms++;$walk($e['elements']??array());}};$walk($reloaded);if($html||$stylesheet||$forms<3){throw new RuntimeException('Hero modernization persistence verification failed.');}
    if(class_exists('\\Elementor\\Plugin')){\Elementor\Plugin::$instance->files_manager->clear_cache();}$rendered=$adapter->render($post_id);if(false===strpos($rendered,'Air consolidation')||false===strpos($rendered,'What air consolidation is.')){throw new RuntimeException('Modernized Hero/What did not render.');}
    WP_CLI::print_value(array('status'=>'pass','post_id'=>$post_id,'roots'=>count($reloaded),'html_widgets'=>$html,'html_stylesheets'=>$stylesheet,'native_forms'=>$forms,'page_posts_created'=>0));
}
